### ISSUE TITLE
PHPUnit 9+ (for PHP 8 support)

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-framework#10019]
## Overview

Creating this spike to investigate the approach for adopting PHPUnit 9. This is currently the main blocker for _full_ PHP 8 support.

Update: Then do all the work :-)

## Tasks
- See if it's possible to upgrade SapphireTest to use PHPUnit 9
- Our favoured approach is to have CMS tests to also be upgraded (in addition to project code compatibility), so document the reasoning for this in the spike 
- Figure out the best way to move through this upgrade, given that it's assumed to relate to both CMS and project code
  - Do we do a 'big bang' approach?
  - Iteratively upgrade, prioritising project code use before CMS code?
- Understand the implication of this change for people who are currently using SapphireTest for their own projects
  - Assuming we'll need a comms plan to advise that adding PHPUnit 9 support, we'll need to explicitly move away from supporting out of date PHP versions (assuming PHPUnit isn't compatible with these versions)
- Engage with project developers to understand their current requirements for project testing
-  Investigate what support could be given to projects upgrading to this new version
  - Is docs enough? Or could we provide an upgrade helper if it's expected to be a challenge?
- Outline the options for the various ways of releasing the change - should it stay in framework, be in a new module, or something else?

**Timebox: 10 days (including consultation)** 

## Notes
See the related issues:
* [RFC: Deprecate SapphireTest (was: Split unit testing support into silverstripe/test-support)](https://github.com/silverstripe/silverstripe-framework/issues/9668)
* [Use a PHP8 compatible version of phpunit](https://github.com/silverstripe/silverstripe-framework/issues/9832)

### PRs
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10028 (merge first, then update travis-shared)
- [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/205 (merge second)
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1259 (merge third)
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2694 (merge forth)
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1237 (merge fifth)
- [x] https://github.com/silverstripe/silverstripe-elemental/pull/941 (merge sixth)
- [x] https://github.com/silverstripe/silverstripe-assets/pull/462
- [x] https://github.com/silverstripe/silverstripe-config/pull/51
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/338
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/210
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/221
- [x] https://github.com/silverstripe/silverstripe-errorpage/pull/60
- [x] https://github.com/silverstripe/silverstripe-reports/pull/141
- [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/119
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/409 (graphql 3)
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/410 (graphql 4)
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/93
- [x] https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/78
- [x] https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/25
- [x] https://github.com/silverstripe/silverstripe-login-forms/pull/103
- [x] https://github.com/silverstripe/silverstripe-mimevalidator/pull/49
- [x] https://github.com/silverstripe/silverstripe-akismet/pull/37
- [x] https://github.com/silverstripe/silverstripe-auditor/pull/38
- [x] https://github.com/silverstripe/silverstripe-blog/pull/661
- [x] https://github.com/silverstripe/silverstripe-ckan-registry/pull/255
- [x] https://github.com/silverstripe/comment-notifications/pull/42
- [x] https://github.com/silverstripe/silverstripe-comments/pull/329
- [x] https://github.com/silverstripe/silverstripe-content-widget/pull/29
- [x] https://github.com/silverstripe/silverstripe-contentreview/pull/156
- [x] https://github.com/silverstripe/silverstripe-crontask/pull/63
- [x] https://github.com/silverstripe/silverstripe-documentconverter/pull/27
- [x] https://github.com/silverstripe/silverstripe-environmentcheck/pull/71
- [x] https://github.com/silverstripe/silverstripe-externallinks/pull/75
- [x] https://github.com/silverstripe/silverstripe-fulltextsearch/pull/299
- [x] https://github.com/silverstripe/silverstripe-gridfieldqueuedexport/pull/57
- [x] https://github.com/silverstripe/silverstripe-html5/pull/31
- [x] https://github.com/silverstripe/silverstripe-hybridsessions/pull/64
- [x] https://github.com/silverstripe/silverstripe-iframe/pull/56
- [x] https://github.com/silverstripe/silverstripe-ldap/pull/37
- [x] https://github.com/silverstripe/silverstripe-lumberjack/pull/105
- [x] https://github.com/silverstripe/silverstripe-mfa/pull/437
- [x] https://github.com/silverstripe/silverstripe-realme/pull/74
- [x] https://github.com/silverstripe/silverstripe-registry/pull/65
- [x] https://github.com/silverstripe/silverstripe-restfulserver/pull/96
- [x] https://github.com/silverstripe/silverstripe-securityreport/pull/52
- [x] https://github.com/silverstripe/silverstripe-segment-field/pull/59
- [x] https://github.com/silverstripe/silverstripe-serve/pull/28
- [x] https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/154
- [x] https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/49
- [x] https://github.com/silverstripe/silverstripe-spamprotection/pull/80
- [x] https://github.com/silverstripe/silverstripe-spellcheck/pull/48
- [x] https://github.com/silverstripe/silverstripe-subsites/pull/471
- [x] https://github.com/silverstripe/silverstripe-tagfield/pull/194
- [x] https://github.com/silverstripe/silverstripe-taxonomy/pull/76
- [x] https://github.com/silverstripe/silverstripe-textextraction/pull/65
- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/81
- [x] https://github.com/silverstripe/silverstripe-userforms/pull/1117
- [x] https://github.com/silverstripe/vendor-plugin/pull/47
- [x] https://github.com/silverstripe/silverstripe-versionfeed/pull/67
- [x] https://github.com/silverstripe/silverstripe-webauthn-authenticator/pull/95
- [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/207
- [x] https://github.com/silverstripe/cwp-agencyextensions/pull/70
- [x] https://github.com/silverstripe/cwp/pull/307
- [x] https://github.com/silverstripe/cwp-core/pull/101
- [x] https://github.com/silverstripe/cwp-pdfexport/pull/22
- [x] https://github.com/silverstripe/cwp-search/pull/40

Remove dms polyfill
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1239
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10139
- [x] https://github.com/silverstripe/silverstripe-reports/pull/142
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/345

Rerun after removing polyfills above
- [x] https://github.com/symbiote/silverstripe-advancedworkflow/pull/454
- [x] https://github.com/symbiote/silverstripe-gridfieldextensions/pull/327
- [x] https://github.com/symbiote/silverstripe-multivaluefield/pull/76
- [x] https://github.com/symbiote/silverstripe-queuedjobs/pull/362
- [x] https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/52
- [x] https://github.com/bringyourownideas/silverstripe-maintenance/pull/167
- [x] https://github.com/dnadesign/silverstripe-elemental-userforms/pull/56
- [x] https://github.com/silverstripe/silverstripe-widgets/pull/187
- [x] https://github.com/tractorcow-farm/silverstripe-fluent/pull/736

Rerun after polyfill removed
- [x] https://github.com/silverstripe/recipe-cms/pull/51
- [x] https://github.com/silverstripe/recipe-core/pull/68
- [x] https://github.com/silverstripe/recipe-authoring-tools/pull/15
- [x] https://github.com/silverstripe/recipe-blog/pull/28
- [x] https://github.com/silverstripe/recipe-collaboration/pull/13
- [x] https://github.com/silverstripe/recipe-content-blocks/pull/19
- [x] https://github.com/silverstripe/recipe-form-building/pull/15
- [x] https://github.com/silverstripe/recipe-reporting-tools/pull/21
- [x] https://github.com/silverstripe/recipe-services/pull/15
- [x] https://github.com/silverstripe/silverstripe-installer/pull/310
- [x] https://github.com/silverstripe/recipe-solr-search/pull/2
- [x] https://github.com/silverstripe/silverstripe-security-extensions/pull/37

Archive controller policy
- [ ] https://github.com/silverstripe/silverstripe-controllerpolicy/pull/34
- [x] https://github.com/silverstripe/recipe-kitchen-sink/pull/3

**Comment by emteknetnz** [comment]
SapphireTest is a wrapper around phpunit that does a couple of things:
- Initialises `TestSession` which, as the name implies, creates a session specially for the test
- Handles silverstripe things like temporary database and loading database fixtures.
- Has a handful of Silverstripe util methods such as `public static findEmail()` which sees if emails sent in unti tests were sent to the `TestMailer`

SapphireTest extends the phpunit class TestCase, so the vast bulk of assertions and the like is just phpunit

I'm pointing this out specifically for this `Engage with project developers to understand their current requirements for project testing` - This seems like it implies we should be looking to add extra functionality to SapphireTest as part of this spike.  I'd be very against doing this at this stage as what we actually want to do is just ensure that existing unit tests work on phpunit 9 with as little friction as possible.  Feature development should be done separately, though I don't even think we should look to 'enhance' SapphireTest as it's just a wrapper.  PHPunit 9 is the enhancement.

**Comment by emteknetnz** [comment]
I've made very good progress getting dual support for both phpunit5 and phpunit9 - both are currently passing in travis (php 7.1 in phpunit 5, php 7.4 and 8.0 are running phpunit 9 https://travis-ci.com/github/silverstripe/silverstripe-framework/builds/233625826

The core of this solution is to have 2 separate versions of SapphireTest (and other classes such as FunctionalTest) within the same SaphireTest.php file on the `Silverstripe\Dev` namespace, and dynamically load the correct one via `class_exists()` checks

phpunit5 and phpunit9 have different API, the main things being:
- functions such as `setUp()` have gone from no return type to having a `: void` return type
- quite a few functions were deprecated and removed, along with the `@expectedException` annotation

There's no way around the fact that we need to update all the unit tests in some capacity.  The can be mostly achieved with a global regex find and replace, though plenty of unit tests needed some additional work.

Where it made sense, I've added some forwards-compatible methods to the phpunit 5 version of SapphireTest, and some backwards compatible methods to phpunit 9 SapphireTest

**Comment by emteknetnz** [comment]
SapphireTest is a wrapper around phpunit that does a couple of things:
- Initialises `TestSession` which, as the name implies, creates a session specially for the test
- Handles silverstripe things like temporary database and loading database fixtures.
- Has a handful of Silverstripe util methods such as `public static findEmail()` which sees if emails sent in unti tests were sent to the `TestMailer`

SapphireTest extends the phpunit class TestCase, so the vast bulk of assertions and the like is just phpunit

I'm pointing this out specifically for this:
> Engage with project developers to understand their current requirements for project testing`

This seems like it implies we should be looking to add extra functionality to SapphireTest as part of this spike.  I'd be very against doing this at this stage as what we actually want to do is just ensure that existing unit tests work on phpunit 9 with as little friction as possible.  Feature development should be done separately, though I don't even think we should look to 'enhance' SapphireTest as it's just a wrapper.  PHPunit 9 is the enhancement.

**Comment by emteknetnz** [comment]
Most modules have the following for require-dev:
```
"sminnee/phpunit": "^5.7.29",`

or

"sminnee/phpunit": "^5.7.29",
"sminnee/phpunit-mock-objects": "^3.4.9",
```

This is going to cause composre conflicts with `phpunit/phpunit": "^9", since some modules may still have the sminnee version while others have the phpunit version.  We can solve this via an intermediary testing module.

Recommend we take the existing "silverstripe/recipe-testing" which is
"require": {
    "silverstripe/recipe-plugin": "^1",
    "silverstripe/recipe-core": "^1@dev || ^4@dev",
    "sminnee/phpunit": "^5.7.29",
    "sminnee/phpunit-mock-objects": "^3.4.9",
    "silverstripe/behat-extension": "^4.4",
    "silverstripe/serve": "^2.2",
    "squizlabs/php_codesniffer": "^3"
}

And make the following changes:
- retire it
- split it into "php-testing" and a "behat-testing" modules
- release two major version, one for phpunit 5 version and another for phpunit 9
- Remove recipe-plugin and recipe-core as requirements
- Require framework instead
- Add "replace": { "<module>": "*" } which conveniently removes a module from installing, which prevents conflicts

**"silverstripe/php-testing" ^1**

"require": {
    "php": "^7.1",
    "silverstripe/framework": "^4",
    "sminnee/phpunit": "^5.7.29",
    "sminnee/phpunit-mock-objects": "^3.4.9",
    "squizlabs/php_codesniffer": "^3"
}
"replace: {
    "phpunit/phpunit": "*"
}

**"silverstripe/php-testing" ^2**

"require": {
    "php": "^7.3 || ^8",
    "silverstripe/framework": "^4.10",
    "phpunit/phpunit": "^9",
    "squizlabs/php_codesniffer": "^3"
}
"replace": {
    "sminnee/phpunit": "*",
    "sminnee/phpunit-mock-objects": "*",
}

**"silverstripe/behat-testing" ^2**

"require": {
    "silverstripe/framework": "^4",
    "silverstripe/behat-extension": "^4.4",
    "silverstripe/serve": "^2.2",
}

#### Modules:
Add the following to all modules require-dev so they work on any version of php 7.1 to 8+
"silverstripe/php-testing": "^1 || ^2"

#### Projects:
Projects are going to vary depending on how long ago there were setup.  If using installer

https://github.com/silverstripe/silverstripe-installer/blob/4.3/composer.json
"require-dev": {
    "phpunit/phpunit": "^5.7",
}

https://github.com/silverstripe/silverstripe-installer/blob/4.5/composer.json
"require-dev": {
    "phpunit/phpunit": "^5.7",
    "sminnee/phpunit-mock-objects": "^3.4.5"
},

https://github.com/silverstripe/silverstripe-installer/blob/4.8/composer.json
"require-dev": {
    "sminnee/phpunit": "^5.7",
    "sminnee/phpunit-mock-objects": "^3.4.5"
},

That will all continue to work with the dual versions of SapphireTest while they're on php 7.  When they upgrade to php8, we'll need to make it clear for them to change to "phpunit/phpunit": "^9" and remove the phpunit-mock-objects fork (it's now part of phpunit/phpunit core).  We probably shouldn't recommend they use "silverstripe/php-testing" since that's more intended for internal module use, not project use, and we want the flexibility to change this at will later.

**Comment by maxime-rainville** [comment]
I had high level overview. Valiant effort in trying to keep both PHPUnit 5.7 and PHPUnit 9 support. 

However, I suspect we might have reach an impasse where we force people to upgrade to PHPUnit 9 and break some APIs along the way.

Maybe there's a way we can split the `SilverStripe\Dev` namespace into its own module. This would allow us to release a PHPUnit 5.7 compatible version under a `1` branch and a `PHPUnit9` version under a `2` branch. Framework could allow you to install either the 1 or 2 branch.

If that's not possible, I think we need to seriously look at breaking SEMVER here and drop support for PHP 7.1 and 7.2.

**Comment by emteknetnz** [comment]
> I suspect we might have reach an impasse where we force people to upgrade to PHPUnit 9 and break some APIs along the way

Correct, the impasse is upgrading to php8, which developers do understand is a potentially breaking change to their both their code and some requirements

> Maybe there's a way we can split the SilverStripe\Dev namespace into its own module. This would allow us to release a PHPUnit 5.7 compatible version under a 1 branch and a PHPUnit9 version under a 2 branch. Framework could allow you to install either the 1 or 2 branch.

I'm not sure this would achieve what we want it to?  Presumably we'd have a requirement in framework of `"silverstripe/dev": "^1 || ^2" - this would default to ^2 which would be php7.4 compatible and use phpunit9, thus breaking their unit tests.  Since sminnee/phpunit is merely a dev requirement, I don't think it would be used in any way to restrict the version of silverstripe/dev installed.  This means that a site with phpunit 5 tests that simply ran `composer update` with no modification to their composer.json file just broke their tests, so this is a breaking change during a minor upgrade.

> If that's not possible, I think we need to seriously look at breaking SEMVER here and drop support for PHP 7.1 and 7.2.

It doesn't make a difference? Let's say we did this and we release phpunit 9 version of SapphireTest in framework 4.10.  Well if my site is on php7.4 when I run `composer update` my tests break.  

Again, the correct time to break the tests is during a sites upgrade to php8, and not merely `composer update`

**Comment by emteknetnz** [comment]
> There's precedent for doing this as well with our previous major releases of GraphQL

We'll, we haven't actually released this yet so we don't know what the fallout from this will be  Probably not that bad because most end users won't notice the change in graphql, only those who actually have a custom graphql endpoint which is probably a fairly small number.  Majority of sites will just be using graphql for asset-admin and it won't need to do any code changes.  For a small number of sites though this will be a breaking change, though there is a relatively easy fix of just specify ^3 for graphql.

If anything the precedent for graphql is what I'm proposing we do here, which is dual version support, as messy as it is.

> asset permalink work

Was that to do with the hash being introduced in the url on the public asset store?  Yeah that was not a good experience.  That was a change got reversed in 4.4 cos it broke peoples sites if I remember correctly?

> 4.9.0 branch until PHP 7.4 is EOL

So force people to upgrade to php8 if they want framework 4.10?  That seems like we're just adding in a hurdle to upgrade and adding significant maintenance headache to ourselves

What happens if there's a security patch we release that requires an API addition?  We break semver on the 4.9 branch?

This seems particularly nasty when we're up to say version 4.13 and we need to backport something to that old 4.9 version we still need to support.  This is very nasty IMO.  We're effectively making 4.9 the end of the road for php7.

> we can just put a conflict statement in the v2 branch to disallow the installation of sminee/phpunit

Would need to validate this, though I think because it's a dev requirement it'll behave differently.  Dev requirements of required modules aren't considered when doing a `composer install`

Even if dev requirements are considered specifically for `conflict`, it's not fail proof because people can still do `composer install --no-dev`, write a lock file, and now they're on ^2 instead of ^1.  You could argue it's user error at this point though.


I've provided a solution here which will result in minimal breakages on peoples sites.  I don't really think that a solution that either breaks peoples sites or just prevents them from upgrading is going to get much cmmunity acceptance.

**Comment by maxime-rainville** [comment]
> If anything the precedent for graphql is what I'm proposing we do here, which is dual version support, as messy as it is.

SS4.0 shipped with GraphQL v1. We're not supporting GraphQL v1 and v2 anymore. Part of the rational there was that a library we relied on for our graphQL support wouldn't work with the latest version of PHP. Which is exactly the situation we're in now.

> Was that to do with the hash being introduced in the url on the public asset store? Yeah that was not a good experience. That was a change got reversed in 4.4 cos it broke peoples sites if I remember correctly?

We didn't do that lightly. But there was a fundamental design flaw in assets that couldn't be remedied easily without some upgrade pains.

> So force people to upgrade to php8 if they want framework 4.10?
I'd say 4.10 can support PHP7.4 and up ... with soft support for PHP 7.3 if you don't care about unit test. 

PHP7.3 has been EOL for some time now, so it shouldn't be such a shocking surprise we're dropping support for it.

> What happens if there's a security patch we release that requires an API addition? We break semver on the 4.9 branch?

Adding an API to in a patch release is not great, but sometimes it's necessary to fix a security issue and we've done it in the past.

> I've provided a solution here which will result in minimal breakages on peoples sites. I don't really think that a solution that either breaks peoples sites or just prevents them from upgrading is going to get much community acceptance.

The solution you got there involves a lot of bifurcated logic which we'll be stuck maintaining for a while. We've already been maintaining some weird fork of PHPUnit for some time now ... which we should never have done. I think we are at a stage where we need to have a clean break. 

We're not hanging out devs to dry if we give them support an extra year to make the transition. 

We try our best to support third party libraries and PHP versions for as long as possible, but sometimes there's factors out of our control that makes that impossible.

At some point, we just need to be honest with the community and explain that it's not practical for us to indefinitely maintain old APIs we are inheriting from third party dependencies.

**Comment by emteknetnz** [comment]
> Adding an API to in a patch release is not great, but sometimes it's necessary to fix a security issue and we've done it in the past.

Yeah but you realise that means we essentially have 2 active minor versions, instead of 1?  4.9 would end up sticking around as "supported" for ages along with the actual current minor.  We would be increasing our maintainence burden by doing this.  This I do not agree with at all.

> The solution you got there involves a lot of bifurcated logic which we'll be stuck maintaining for a while

This is not really a problem in practical terms though? SapphireTest doesn't exactly get a lot of work done it - https://github.com/silverstripe/silverstripe-framework/commits/4/src/Dev/SapphireTest.php 

I'd estimate the ongoing "maintainence" work here to be near zero.  Unlike GraphQL, SapphireTest is not in active development.  After all SapphireTest is just a Silverstripe wrapper around PHPUnit to get things like fixtures working

Bulk of the work here is updating all the unit tests to work with phpunit9, which I've already made large inroads into

The major downside to this approach seems to be "more work for CMS squad", however I estimate this extra work to be very low, so it's not really a downside?

Alternative approach you're suggesting here has multiple downsides, including more ongoing maintenance.

**Comment by emteknetnz** [comment]
I've summaries a few approaches below.  I'm obviously biased to the solution I presented in the POC PR's linked above, though I really do think it's the only viable solution as the other approaches are going to cause users an bad upgrade experience where either things break or they can't upgrade.

### Background
1. SapphireTest is a wrapper around a forked version of phpunit5 and mainly does things such as get test session and fixtures to work.  It also utility functions such as seeing if emails were sent by the test mailer.
2. FuntionalTest is an extension of SapphireTest simulates GET and POST request to application being tested
3. phpunit5 is not compatible with php8
4. This lack of compatibility is the major blocker to us saying that silverstripe works with php8
5. We need SapphireTest to work with phpunit9
6. phpunit9 is similar to phpunit5 though there are some funciton signature differences, meaning that projects and module will be required to update their unit tests, even if just to add a `:void` return type to some functions
7. phpunit9 is not compatible with php7.1 or php7.2, though it works with php7.3 and php7.4

### Options

#### Two different versions SapphireTest/FunctionalTest in the framework codebase supported phpunit5 and phpunit9 respectively. Use the correct version depending on the version of phpunit installed**

**Pros:**
- Non-semver breaking change, means that `composer update` will not break your site during an upgrade
- Sites on php7 can upgrade to phpunit9 at their leisure
- Ditto for community modules
- The breaking change of going to phpunit9 is forced at the same time as the breaking change going to php8 where devleopers will expect to have to make some code and dependency modifications.
- We can retain support for older versions of php such as 7.1 until we decide to drop it

**Cons:**
- Duplicate SapphireTest/FunctionalTest files

**Notes:**
- I've already done several PR's for this POC to upgrade the unit tests in modules to both phpunit5 and phpunit9 and those are worked as expected
- SapphireTest and FunctionalTest are very mature, do their job and seem very unlikely to have new functionality added to them any time soon. I've estimated the ongoing maintainence burdern of running duplicate classes as minimal
- This is my recommended because it seems like the only way to maintain a minor upgrade experience for projects

#### Make php7.3 the minimum required for 4.10 - Make a semver breaking change and only include the phpunit9 `SilverStripe\Dev\SapphireTest` in the codebase.  

**Pros:**
- Single SapphireTest and FunctionalTest files

**Cons:**
- Breaking change, bad upgrade experience. Running `composer update` means that unit tests will no longer work on projects.  Developers will need to make code changes.
- This is not how `composer update` should work for minor upgrades.  What's should happen is you upgrade and things still work the same as before, with bugs fixed and additional features added
- Community module maintainers will find their unit tests suddenly breaking if they work out of the vendor folder of a regular silverstripe install

#### Make php8 the minimum required for 4.10 - Make a semver breaking change and only include the phpunit9 `SilverStripe\Dev\SapphireTest` in the codebase.  

**Pros:**
- Single SapphireTest and FunctionalTest files

**Cons:**
- 4.9 becomes the end of the line for sites on php7.  php8 upgrade project required to get to 4.10
- Obvious blocker for adoption for later version, this will annoy people
- We'll still need to backport security fixes to 4.9, for all the sites still on php7, even when we're on version like 4.13 - so we'll end up with 2 current minors and increase the maintainence burden.

**Comment by maxime-rainville** [comment]
## Option A
- I'm pretty sure having two different and contradictory APIs in one release is not SEMVER compliant either.
- We're not going to maintain two sets of unit test forever. We're just delaying the pain for projects.

## Option B 
- PHP 7.3 is already EOL, I would set the minimum to PHP 7.4.

I would combine this with an extra year of support for Silverstripe CMS 4.9
- This would cover critical bug fixes and security fixes
- I would try to combine this with a switch to GraphQL v4 in 4.10

In effect, this gives you a year to:
- migrate your project to a supported version of PHP
- adapt your tests to work with PHP Unit 9
- get your users off IE11
- get your project off GraphQL v3
- (get off Swiftmailer maybe)

I think this is better because it gives clear guidance and timeframes for projects to move off deprecated dependencies.

## Option C
- I don't think we should do that.

**Comment by maxime-rainville** [comment]
When I did my initial review, I missed the part where we add a bunch of polyfills to restore API that PHPUnit has deprecated. I would like some clarity about how we want to approach this.

Copying deprecated APIs from PHPUnit into our own codebase and adding them to our own API would be a terrible mistake. We already have a gigantic API surface to maintain. The last thing we should be doing is taking over APIs that the PHPUnit maintainer doesn't want to look after.

Alternatively, we could backport some of the newer APIs back to the `sminne/phpunit` and update all our unit test to move away from using deprecated APIs. Wasting time to add things would be painful but it would be less bad than adding to our API surface.

On a related note, the [PHPUnit support timeline](https://github.com/sebastianbergmann/phpunit/blob/54f46a7e6afdef9abc8e33751c3fe73442ef9746/composer.json#L25) seems to indicate that they release a new major in February of most years. We should expect a PHPUnit10 in Feb 2022. Looking at their [master branch](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json) looks like it will drop support for PHP7 altogether.

We probably need to decide now what we want to do PHPUnit10. This means potentially supporting 3 different versions of PHPUnit simultaneously. Or we skip PHPUnit10 altogether and we have this entire discussion again in a year or two when PHPUnit 9 support gets deprecated.

**Comment by emteknetnz** [comment]
Looking at my previous notes on https://github.com/silverstripe/silverstripe-framework/pull/10028 - it's basically to prevent having to rewrite large chunks of core unit tests which need to work in BOTH phpunit5 and phpunit9.  Yes we could update them to work with straight phpunit9 functions, but we'd need to update a lot of unit tests (possibly not that bad, maybe find and replace will be good enough.  And then we'd also need to add the forward compatibility polyfills to phpunit5)

Searching in kitchen-sink for
- `assertContains` nets 2021 results
- `assertNotContains` nets 401 results
- `assertInternalType` nets 718 results

The backwards compatibility polyfills also make it easier for existing projects to keep their unit tests as is for when they need to migrate to phpunit9.  You could argue this is just being overly nice since they will have to do some work e.g. migrate off the docblocks for expected exceptions

> Wasting time to add things would be painful but it would be less bad than adding to our API surface.

It's probably worth re-exploring some 'find and replace' to migrate everything to phpunit9 to see if it's a semi-quick win, though it's certainly more work and I don't see backwards compatibility polyfills as really that bad maintainence wise (and obviously they're way better migration wise).  I wouldn't automatically assume doing a bunch of extra work "would be less bad", particularly when there's an opportunity cost associated with doing work.

`assertArraySubset` is definately a specif replaced with a backwards compatibility community module. It's a complex assertion and I want to keep it as we'll just end up wasting time duplicating this function if we don't.

**Notes copied from previous comment:**

assertInternalType() and assertNotInternalType() were removed - upgrade guide - sebastianbergmann/phpunit#3368 - though I've added backwards compatible versions - we've added a backwards compatible version of assertInternalType() to SapphireTest to support existing core unit tests on phpunit5, but not for assertNotInternalType() which wasn't used in any core tests

assertArraySubset() has been removed. It can be polyfiled for backwards compatibility on individual SapphireTest classes with a trait in a module:

composer require --dev dms/phpunit-arraysubset-asserts

```
use DMS\PHPUnitExtensions\ArraySubset\ArraySubsetAsserts;

class MyTest extends SapphireTest
{
    use ArraySubsetAsserts;
```

**phpunit10**
It's too soon to plan from phpunit10 since it's still in development.  For all I know it'll work out of the box with what we have with phpunit9. Or maybe it won't work at all?  Given that the world did not end when we didn't support phpunit 6, 7 and 8 it's probably safe to assume that skipping 10 wouldn't be too bad.  Regardless we can worry about this much later.

**Comment by maxime-rainville** [comment]
> The backwards compatibility polyfills also make it easier for existing projects to keep their unit tests as is for when they need to migrate to phpunit9. You could argue this is just being overly nice since they will have to do some work e.g. migrate off the docblocks for expected exceptions

If we do that, we're functionally taking over the deprecated APIs from PHPUnit and committing to supporting them. There's probably some other deprecated PHPUnit APIs that we're not using that some people out there might be using.

I would rather take the extra time needed to convert all our test coverage to the PHPUnit9 equivalent and then fully drop PHPUnit5 in Dec 2022.

> It's too soon to plan from phpunit10 since it's still in development. For all I know it'll work out of the box with what we have with phpunit9. Or maybe it won't work at all? Given that the world did not end when we didn't support phpunit 6, 7 and 8 it's probably safe to assume that skipping 10 wouldn't be too bad. Regardless we can worry about this much later.

The "world did not end when we didn't support phpunit 6, 7 and 8" because we kept jumping through hoops to keep our PHPUnit fork working. I would rather avoid being in this position going forward. 

"Much later" is probably going to be Feb 2022 so it's not that far away. My guess is that PHPUnit 9 will go in limited support when PHPUnit 10 is release.

I'm fine with taking the risk of "maybe not supporting PHPUnit 10" if we don't think that's essential. But if we think PHPUnit 10 is going to be essential, then the decision we make here could have lot of downstream effects and we should try to figure out what those will be.

**Comment by emteknetnz** [comment]
Max pointed out

https://github.com/Yoast/PHPUnit-Polyfills

Idea would be to add all the traits to the phpunit5 version of sapphiretest and remove my forwards compat polyfills.

We could probably also add wrapper functions in phpunit5 sapphire test with deprecation notices and just call parent::func().  that would help during project/module migration to identify which functions needs to be changed

**Comment by maxime-rainville** [comment]
After much discussion, we've come up with a variation of Option A.

# Option D - Convert all supported modules unit test to PHPUnit 9 while maintaining PHPUnit 5.7 support

- We approve https://github.com/silverstripe/silverstripe-framework/issues/10102 and drop support for PHP7.1 and PHP 7.2 in Silverstripe CMS 4.10
  - PHPUnit 9 requires PHP7.3 or higher
- All our test coverage is converted to the newer PHPUnit 9 API in the Silverstripe CMS 4.10 release
  - It would be impossible to run supported module test suites against PHPUnit 5.7
- We define `SapphireTest`, `FuncitonalTest` and other related classes with bifurcated implementations which allows them to keep working with PHPUnit5.7
  - This would allow projects that are not yet ready to upgrade to PHPUnit 9 to keep running their existing test suite against PHPUnit 5.7.
  - This bifurcated implementations will have a hard end date of December 2022. At which point, projects would have no choice but to upgrade to PHPUnit 9 if they want to stay on a supported Silverstripe CMS release.

**Comment by maxime-rainville** [comment]
I was just listening to a talk about internationalisation and apparently the text extractor relies on PHPUnit to work. So we have to make sure that it still works with PHPUnit 9.

**Comment by emteknetnz** [comment]
@maxime-rainville I'm thinking option B is the way to go here, it's slightly more work though I think it's technically more correct, and means we can get rid of the 2 classes in one file thing

**Comment by maxime-rainville** [comment]
In a perfect world, we would just split up the test suite into it's own module (Option B). Unfortunately, that's kind of hard to achieve without doing a major.

Option A is appropriate since we won't have a way to test modules against older releases of framework. So I'm happy with bumping all the module to require `"silverstripe/framework": "^4.9"`

**Comment by emteknetnz** [comment]
^4.10 :-)

**Comment by maxime-rainville** [comment]
We'll spin up the controller policy bit in a separate PR.

**Comment by davejtoews** [comment]
> Some chance of it being problematic in the interim before we tag 4.10 as these modules CI will be installing 4.x-dev instead of a stable version, though probably a non-issue

Chiming in here to challenge "probably a non-issue". I was doing some maintenance and bumped a couple of modules up a minor version and suddenly found myself running bleeding edge, non-stable versions of SilverStripe core modules.

I caught the problem in two modules, but from the looks of this thread it's bigger than that.

* https://github.com/symbiote/silverstripe-gridfieldextensions/issues/328
* https://github.com/silverstripe/silverstripe-lumberjack/issues/106

**Comment by emteknetnz** [comment]
Hey @davejtoews - could you check your `composer.json` file - we recommend the following:
```
"prefer-stable": true,
"minimum-stability: "dev"
```
silverstripe/framework 4.10.0 hasn't yet been released, so the new "silverstripe/framework": "^4.10" constraint should behave as follows:
`"prefer-stable": true` - should install `4.9.1`
`"prefer-stable": false` - should install `4.x-dev`

Let me know if this isn't behaving as expected

**Comment by emteknetnz** [comment]
@davejtoews Sorry about this happening.  We've written an explanation of what went wrong and why [here](https://docs.silverstripe.org/en/4/changelogs/beta/4.10.0-beta1/#unstable-framework).

We recommend setting `silverstripe/framework` to `~4.9.0` until `4.10.0` has been released, or setting `minimum-stability` to `stable`
