### ISSUE TITLE
Broken builds

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10278]
There are several broken builds currently. This ticket focuses on the broken builds on modules which are included in silverstripe/recipe-kitchen-sink.

## Broken builds (minor release branch e.g. `4`)
- [ ] [silverstripe/asset-admin](https://app.travis-ci.com/github/silverstripe/silverstripe-asset-admin/builds/249846291)
- [x] [silverstripe/framework](https://app.travis-ci.com/github/silverstripe/silverstripe-framework/builds/249601294)
- [x] [silverstripe/admin](https://app.travis-ci.com/github/silverstripe/silverstripe-admin/branches)
- [x] [silverstripe/userforms](https://app.travis-ci.com/github/silverstripe/silverstripe-userforms/branches)
- [x] [silverstripe/totp-authenticator](https://app.travis-ci.com/github/silverstripe/silverstripe-totp-authenticator/branches)
- [x] [silverstripe/installer](https://app.travis-ci.com/github/silverstripe/silverstripe-installer/branches)
- [x] [silverstripe/recipe-kitchen-sink](https://app.travis-ci.com/github/silverstripe/recipe-kitchen-sink/branches)
- [x] [silverstripe/recipe-blog](https://app.travis-ci.com/github/silverstripe/recipe-blog/builds/249414291)

## Broken builds (patch release branch e.g. `4.10`)
- [x] [silverstripe/admin](https://app.travis-ci.com/github/silverstripe/silverstripe-admin/branches)
- [x] [dnadesign/silverstripe-elemental](https://app.travis-ci.com/github/silverstripe/silverstripe-elemental/branches)
- [x] [silverstripe/fulltextsearch](https://app.travis-ci.com/github/silverstripe/silverstripe-fulltextsearch/builds/248289593)

## Acceptance criteria
- [x] all builds listed above are passing on the minor release branch and more recent patch release branch.

## PRs
- [x] silverstripe/silverstripe-testsession#74
- [x] silverstripe/silverstripe-behat-extension#213
- [x] silverstripe/silverstripe-totp-authenticator#90
- [x] https://github.com/silverstripe/silverstripe-assets/pull/487
- [x] https://github.com/silverstripe/silverstripe-postgresql/pull/127
- [x] https://github.com/silverstripe/silverstripe-mfa/pull/453
- [x] silverstripe/silverstripe-elemental#979
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10287
- [x] https://github.com/silverstripe/silverstripe-framework/pull/10291
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1268

## Note
- Cannot replicate the silverstripe/installer behat failure either locally or using [github actions ci](https://github.com/emteknetnz/silverstripe-installer/runs/6106382330?check_suite_focus=true#step:12:533)

**Comment by GuySartorelli** [comment]
The elemental build has broken in a way very similar to silverstripe/silverstripe-elemental#954 - at least for the publish mutation. I'm hoping the fix that was put in place for `4` will work here.

**Comment by emteknetnz** [comment]
Linked PRs have been merged
