### ISSUE TITLE
PHP 8.1 Tidy up

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-framework#10294]
Parent issue for pull-requests to tidy up PHP 8.1 work

### TODO
- [x] Get tractorcow/classproxy - need either a 0.1.3 tag OR proxy-db to use ^1 - see linked PR below.  If we update proxy-db, also need pull-requests to update silverstripe/auditor and silverstripe/fulltextsearch which both require proxy-db
- [x] Ensure silverstripe/recipe-solr-search requires 3.10.x-dev of fulltextsearch (should happen automatically as part of cow release)
- [x] https://app.travis-ci.com/github/silverstripe/silverstripe-installer/jobs/568330265#L1305 (fixed in graphql PR below)

### Notes on trying to get travis ci to fail on deprecations:

Depite [this PR](https://github.com/silverstripe/silverstripe-travis-shared/pull/38/files) - we still have green jobs with [deprecation warnings](https://app.travis-ci.com/github/silverstripe/silverstripe-installer/jobs/568330265#L1305)

I don't think we can get phpunit to properly fail on deprecation notices - I've tried the following custom error handler in `SapphireTest.php` along with `--fail-on-warning`
```
set_error_handler(function (int $number, string $message) {
    trigger_error($message, E_USER_WARNING);
}, E_DEPRECATED | E_USER_DEPRECATED);
```
However tests are still green despite the presence of `Warning: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated`

I've also tried updating `phpunit.xml.dist` - https://phpunit.readthedocs.io/en/9.5/configuration.html - however `failOnWarning="true"` which is equally useless as `--fail-on-warning` and `convertDeprecationsToExceptions="true"` is too brutal and causes phpunit to exit

### PRs
- [x] https://github.com/bringyourownideas/silverstripe-composer-update-checker/pull/63
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/461
- [x] https://github.com/silverstripe/silverstripe-installer/pull/320
- [x] https://github.com/silverstripe/silverstripe-graphql/pull/462
- [x] https://github.com/tractorcow/silverstripe-proxy-db/pull/3
- [x] https://github.com/silverstripe/recipe-blog/pull/31
- [x] https://github.com/silverstripe/silverstripe-installer/pull/321
- [x] https://github.com/symbiote/silverstripe-multivaluefield/pull/81
- [x] https://github.com/silverstripe/silverstripe-serve/pull/30
- [x] https://github.com/silverstripe/silverstripe-config/pull/57
- [x] https://github.com/silverstripe/vendor-plugin/pull/53
- [x] https://github.com/silverstripe/silverstripe-userforms/pull/1143
- [x] https://github.com/silverstripe/recipe-solr-search/pull/7
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/109
- [x] https://github.com/silverstripe/silverstripe-auditor/pull/43
- [x] https://github.com/silverstripe/silverstripe-fulltextsearch/pull/322

**Comment by GuySartorelli** [comment]
PRs are merged, but there is an acceptance criterion that can't be ticked off until the cow beta release either does or does not update `composer.json` in `recipe-solr-search`.

**Comment by GuySartorelli** [comment]
`recipe-solr-search` is correct in `4.11`. All acceptance criteria met.
