### ISSUE TITLE
Create a meta .github repo for the Silverstripe organisation

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-framework#10424]
Currently each repository has its own meta files such as "CONTRIBUTING", "SECURITY" etc which are (or should be) identical - or those may be missing entirely. There's no standard or any process for updating them. Ideally those should be standard and all point to the relevant docs.

- A `.github` repository allows us to have [default meta files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).
- It also allows us to have a README.md file at the organisation level which will display on https://github.com/silverstripe. We can use this to give a general overview of Silverstripe CMS, how to get started, how to contribute, etc.
- Finally, it can be used as a centralised space for conversations that don't really apply to any given repository. Historically those discussions have been held in the silverstripe/silverstripe-framework repository.

## Acceptance Criteria
- [ ] A new `.github` repository exists
- [ ] An organisation-level README.md file exists with some helpful information
- [ ] Appropriate default meta files have been created
- [ ] The existing meta files in individual repos are removed, so that the default files can apply

**Comment by GuySartorelli** [comment]
https://github.com/silverstripe/.github
