### ISSUE TITLE
table_name property for each DataObject

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5419]
## Acceptance criteria

 * Data objects can take a `table_name` property.
 * `table_name` can be specified in the yaml config.
 * If `table_name` isn't specified, use SS3 naming convention

## Exclusions

 * Better defaults than SS3 not needed yet (not critical for alpha2)
 * Tables don't need to be automatically renamed (see #5589)

## Description

Once we start putting `DataObject` subclasses into namespaces, we're going to end up with ungainly table names, containing `\` characters. This functions correctly in SilverStripe 3, and some projects have used it, but it's not especially elegant.

I think the best first step is to introduce a `table_name` property, per DataObject class, that will be used in place of the class name in all generated queries.

Anyone who is using hand-rolled queries may trip over this, but I see this as yet another reason not to use hand-rolled queries. Some documentation about alternatives to hand-rolled queries (e.g. starting with a `SQLSelect` generated by the ORM and manipulating it) should be included in the docs.

----

Beyond this, I think it would be good to have some kind of mechanism for swapping out the table name generator functionality. Off the top of my head, I can think of a few examples:

 * Preserve the existing functionality, `\`s and all.
 * Replace `\` with `_` in class names
 * Use only the base name of the class
 * Apply a psr-4 style set of maps between short prefixes and long namespace prefixes
 * Any of the above, converted to lower case

I think that this can be broken out as a separate card, and for our initial namespacing work, we can simply map out bc-preserving `table_name` values in a yaml file.

It's probably worth raising this as a separate ticket, but it might be premature to do so until the table_name functionality is built.

## Related

 * Legacy reference (for SilverStripe internal team only, sorry): https://silverstripe.atlassian.net/browse/OSS-1856

## Tasks

 * [ ] Upgrading notes - https://github.com/silverstripe/silverstripe-framework/pull/5646
 * [ ] Implement `table_name` - https://github.com/silverstripe/silverstripe-framework/pull/5646
 * [ ] Default to current table name for core model
 * [ ] Update hard-coded references to core tables (e.g. SiteTree / Member) so that custom table_name is respected.

**Comment by micmania1** [comment]
I think using a property for this could potentially be a cause of frustration for developers. For example, if you forget to set it on a subclass, then its going to use the `table_name` property of its parent class and the developer might not realise why. It also takes away the complete automation that makes SilverStripe enjoyable to use.

Another option which is similar, would be to add a `getTableName()` method which defaults to one of the options you've suggested for table name generation. This gives the developer the power to control the table name, but also keeps the automation.

A completely different idea i'd like to throw in the mix is that this could be solved by removing the dependency of `DataObject` from `DataList`. If `DataList` was aware of how the tables were mapped to classes, then that would be enough.

eg.
```
DataList::map_table_name([
    MyDataObject::class => 'MyTable',
]);
```

This would mean changing `DatabaseAdmin` (also heavily coupled to `DataObject`) to use `DataList` as its source of information, rather than doing the heavy lifting itself and relying on `DataObject`.

A benefit of this way besides the decoupling would be that developers could then control table names in one place from `_config.php` and would also give them access to table names of core classes. It could open up new possibilities like creating tables from classes besides `DataObject` given that `DataList` would know how to map that class to a table.

*Disclaimer: DataList might not be the best place to put this information, but the gist is that it could be de-coupled from DataObject.*

**Comment by sminnee** [comment]
> I think using a property for this could potentially be a cause of frustration for developers. For example, if you forget to set it on a subclass, then its going to use the table_name property of its parent class and the developer might not realise why. It also takes away the complete automation that makes SilverStripe enjoyable to use.

I agree that it would need to be a config option that doesn't inherit. This is similar semantics to how `$db` is handled and the config system allows for it, so that's no big deal. We'd want to test for it explicitly in any test cases we set up.

> Another option which is similar, would be to add a getTableName() method which defaults to one of the options you've suggested for table name generation. This gives the developer the power to control the table name, but also keeps the automation.

This makes the problem you identified worse, so it doesn't get my vote. It's also going to be important to be able to alter the table name of classes provided by a module, in cases where the default table name selection conflicts with those chosen by another module. Yaml config overrides allow for this, a table name method doesn't.

> A completely different idea i'd like to throw in the mix is that this could be solved by removing the dependency of DataObject from DataList. If DataList was aware of how the tables were mapped to classes, then that would be enough.

This idea has merit, but it's a much bigger change—to be internally coherent and get the most value of the change we'd want to approach it as a refactoring of the ORM from an ActiveRecord pattern to a DataMapper pattern—and so I would see it as building on the much simpler idea described in this ticket, rather than being an alternative to it. In particular, I want to find the shortest path that we can take to let us start namespacing dataobject subclasses.

**NOTE:** if we proceed with #5422, then the config option should probably be `tableName` instead. ;-)

**Comment by kinglozzer** [comment]
I think this all sounds good. Uninherited config solves the issue of inheriting “parent” table names and keeps it easy to override, the table name “strategy” service keeps the nice developer experience.

> Anyone who is using hand-rolled queries may trip over this, but I see this as yet another reason not to use hand-rolled queries.

Given that getting the table name would be as simple as `singleton('MyDataObject')->getTableName()` (or it could be a static method?), I think this is a non-issue anyway.

> Apply a psr-4 style set of maps between short prefixes and long namespace prefixes

Does this mean that we might map, for example, the `SilverStripe\Framework\Model` prefix to `core`, or `SilverStripe\Cms` to `cms` so that we end up with (namespaces are just examples!):

- `SilverStripe\Framework\Model\Member` -> `core_member`
- `SilverStripe\Cms\Model\SiteTree` -> `cms_sitetree`
- `MyProject\Model\Product` -> `myproject_model_product` (unless you set up your own mapping)

That would probably be the nicest default IMO, I don’t like the thought of unnecessarily verbose table names (I don’t have any reasoning there, I just don’t).

**Comment by sminnee** [comment]
> Does this mean that we might map, for example...

Yeah, that's the idea. I think that the nicest default is probably one that doesn't necessitate table renames, but it provides a good scheme for people to resolve the issue. Or, we might have a different default for new projects created in SS4 / make it easy to choose a more robust default.

**Comment by tractorcow** [comment]
I'm a bit late to the discussion, but hope my view can still be useful!

In my experience, there are a LOT of places where we map table -> class and class -> table. The operation should be as simple and quickly reversible as possible, and I would see a too-flexible configuration to likely be unnecessary. For instance, there is no case where we would absolutely need full control over the table name, such as a class `Project\Model\MyObject` having the table name `SomeUnrelated_TableName`.

The standard approach in API development, as is my preference, is convention over configuration, at least where it solves the problem at hand. :)

> Apply a psr-4 style set of maps between short prefixes and long namespace prefixes

This is my preference by far. By default (as in 3.x) the table name of any class matches it's FQN. However, you can setup aliases for specific namespaces to explicitly simplify them in groups.

Thus the approach is to specify aliases for namespaces RATHER than per-table. Because a project will have a set of namespaces that is MUCH smaller than the list of classes, the amount of configuration is simpler.

I'm happy with `\` being in the table name, as such replacement is not a problem we need to solve, and thus leaving it in place reduces complexity.

Example:

```yaml
DataObject:
  table_namespaces:
    SilverStripe\Framework: 'Framework'
    SilverStripe\Model\Security: 'Security'
```

Thus a table with the name `Framework\Object` can be quickly mapped to classname `SilverStripe\Framework\Object`, and `Framework\Member` to `SilverStripe\Model\Security\Member`.

Mapping class to table is even simpler, which is a simple iteration over all mappings and substituting the first matching string replacement.

Given that most mappings will be from class -> table, I'd probably have the namespace alias as the key.

I am against having "php overridable" methods on objects for getting table name, as they aren't reversible. That is, given the result of a getTableName(), you can't deterministically find the object that produced it.

**Comment by sminnee** [comment]
> In my experience, there are a LOT of places where we map table -> class and class -> table. The operation should be as simple and quickly reversible as possible.

Good point - we'll want to ensure there's a quick way to reverse the operation. Probably some kind of look-up table of all the registered data classes, would make sense. That'd also make it easier to detect collisions.

> I'm happy with \ being in the table name, as such replacement is not a problem we need to solve, and thus leaving it in place reduces complexity.

I think that's pretty gross - underscores are are more in keeping with accepted conventions - and although I could tolerate it as one of the options available to site maintainers, I'd hope there would be others. If you were okay with backslashes in tables then you could just use the system as is. So, yes, this ticket only exists because of a desire to solve that problem. ;-)

Furthermore, my preference would be that the table names of the existing data classes provided in core don't change: so I'd want to see `SilverStripe\Security\Member` mapped to a `Member` table. Or, at least, I'd like there to be some configuration that upgraders could apply to make this happen. I expect that something like this will do that:

    DataObject:
      table_namespaces:
        SilverStripe\Security: ''

PS: Security is emphatically **not** a sub-namespace of the model.

**Comment by dhensby** [comment]
As long as the core makes it easy and fool proof to use the pen without needing to know the underlying DB schema, then this is a reasonable solution. 

I'm just worried there are instances when you have to know the table structure (and so make assumptions) when adding sorts or group by and so on...

**Comment by tractorcow** [comment]
> I think that's pretty gross - underscores are are more in keeping with accepted conventions - and although I could tolerate it as one of the options available to site maintainers, I'd hope there would be others. If you were okay with backslashes in tables then you could just use the system as is. So, yes, this ticket only exists because of a desire to solve that problem. ;-)

The problem here is that underscores can actually be a part of the file name; You can't reverse it easily without adding more "if" checks to find actual classes.

I would be fine with double underscore in the table, as an alternative, since that can be easily reversed. I used a similar convention in assets to delimit filename from file variant.

**Comment by sminnee** [comment]
> The problem here is that underscores can actually be a part of the class name; You can't reverse it easily without adding more "if" checks to find actual classes.

No, you need a registry of tables/classes. Then reversing is easy.

**Comment by tractorcow** [comment]
If your registry maps to individual classes, then that would be ok. I would expect it to update itself in that case.

**Comment by tractorcow** [comment]
Checklist of classes to migrate (growing as I check)

* [] ManyManyList
* [] HasManyList
* [] DataQuery
* [] DataList
* [] SearchFilter / subclasses
* [] DBSchemaManager

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/5646

**Comment by tractorcow** [comment]
Regarding this:

> Default to current table name for core model

I expect that when we namespace each model, we should apply the `table_name` as necessary at that point in time.
