### ISSUE TITLE
Apply namespaces to the rest of the model subsystem

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5421]
## Description

The model subsystem has already had namespaces introduced to field types, as part of PHP7 compliance.

Applying namespaces to the rest of the model subsystem is a logical next step.

Note that, as long as we don't yet apply namespaces to any of *the subclasses* of DataObject. #5419 needs to be implemented first.

## Exclusions

 * Updating documentation

## Related

 * Legacy reference (for SilverStripe internal team only, sorry): https://silverstripe.atlassian.net/browse/OSS-1855
 * table_name base implementation: https://github.com/silverstripe/silverstripe-framework/issues/5419

## Tasks

 * [x] Rename `model/` to `orm/`
 * [x] Move out DataObject classes to new `model/` dir (`Image`, `Changeset`)
 * [x] Run upgrader tool against `model/` folder, manually fix any issues which break tests
 * [x] Regression test CMS operation
 * [x] Post PR https://github.com/silverstripe/silverstripe-framework/pull/5734
 * [x] Post to dev list about upcoming change after PR raised but before merging https://groups.google.com/forum/#!topic/silverstripe-committers/t27D84dAdMs https://groups.google.com/forum/#!topic/silverstripe-dev/Ig3ODKBEaT4
 * [ ] Merge PR

Closed with #5734

**Comment by sminnee** [comment]
FYI I've been working on scripting this, as a stress test of https://github.com/sminnee/silverstripe-upgrader.

**Comment by tractorcow** [comment]
My preference is to get everything namespaced, so I'd like #5419 in alpha 2.
