### ISSUE TITLE
Enhancement: Don't allow multiple campaigns with the same name

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5464]
## Acceptance criteria

 * Campaigns are easily distinguish without careful naming from the user
   * De-duplicate
   * Maybe auto-affix a creation date?
   * Maybe allow campaigns without a name identified solely by a date

Set-on-form-submission is fine.

---

There is no indication that there is already a campaign with the same name.

![pasted_image_6_05_16__2_19_pm](https://cloud.githubusercontent.com/assets/555033/15062590/8414fb1c-1395-11e6-850d-c2cd6080bb89.png)

## Tasks

- [x] If a name exists show an error message in the form
- [x] Handle name duplicate in edit form
- [x] Do not redirect use to campaign edit form if there's an error in the form submission response

## Related

- https://github.com/silverstripe/silverstripe-campaign-admin/issues/16

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/17

**Comment by stevie-mayhew** [comment]
Do we want to allow campaigns with the same name and instead attribute a date as part of their title? I know its a bit finicky, but I can see a use for multiple campaigns with the same name (even if we wouldn't do it ourselves)

**Comment by clarkepaul** [comment]
Yup possibly, or just a incremental numbering after the title as in the files area and most computers handling duplications.

**Comment by chillu** [comment]
In general, we need to visualise validation feedback, which means we need the mechanisms for server and client validations in the first place - I've created some cards: https://github.com/silverstripe/silverstripe-framework/issues/5523 and https://github.com/silverstripe/silverstripe-framework/issues/5522

**Comment by phalkunz** [comment]
Wouldn't it make more sense to suffix a campaign name with `-v{n}` where n is integer when the name already exists? We already have this behaviour in Asset Admin.

**Comment by clarkepaul** [comment]
Eventually there will be more fields for which a user can distinguish the difference between campaigns (due date, date created, permissions) so I think a suffix would work good as the most basic step. A message notifying the user that the given name already exists before providing the suggested suffixed name would make a nice addition. 

"That name is already taken. You could use... "
