### ISSUE TITLE
Implement client-side form validation feedback in React forms

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5523]
Likely requires us to choose a React forms library first (some options: https://react.rocks/tag/Form). Could use JSON Schema as part of the form field schema we're generating, as a way to communicate validation constraints from the server to the client. Includes styling through Bootstrap (http://v4-alpha.getbootstrap.com/components/forms/#validation).

Redux Form has [pluggable validation](http://redux-form.com/5.2.5/#/examples/synchronous-validation?_k=edvj7l). Note that we can get quite far with powerful declarative validation, as the popularity of https://github.com/sheadawson/silverstripe-zenvalidator proves.

Overview of adding validation to Redux Form: https://medium.com/@rajaraodv/adding-a-robust-form-validation-to-react-redux-apps-616ca240c124#.v8bfb62m7

**TO DO:** Revisit the size after #5524 is complete.

## Tasks
- [x] Require "Name" on File and Folder detail sidebar in AssetAdmin (split out from https://github.com/silverstripe/silverstripe-asset-admin/issues/156)
- [x] Implement new schema for validation
- [x] Research on a validation library to use
- [x] Implement client side validation logic in Form components to work with schema
- [x] Write unit tests for Validator class

# Related
- Server-side validation: https://github.com/silverstripe/silverstripe-framework/issues/5522
- Implement a React form library: https://github.com/silverstripe/silverstripe-framework/issues/5524

**Comment by flamerohr** [comment]
throwing in this `TODO` I noticed while peer reviewing, so it's not forgotten:
https://github.com/silverstripe/silverstripe-asset-admin/pull/287/files#diff-1725a22613a9ff930ae321601182c714R80

**Comment by flamerohr** [comment]
I've been searching around for a validation library that we could use, some criteria I had in mind were:
* Can provide many basic validation rules
* Can be used with ReactJS
* Documentation reasonably covers API.
* No heavy dependencies is a plus, e.g. no jQuery.
* Extensibility is a plus.

## Recommendation
### [Approve.js](https://github.com/CharlGottschalk/approvejs)
Approve.js is a great candidate that would suit our needs.
It was designed to be a non-intrusive layer for frontend/backend validation, the maintainer himself uses it with `Vue.js`.
The library is extensible, so custom validation rules can easily be added in.
Pros:
* Extensible, can add custom validation rules easily.
* Can customise validation messages as required.
* API is basically passing in an object with the rules contained.
* Returns an object with iterable error messages.
Cons worth noting:
* Young project (published July 2016)
* Their "Test results" documentation page was broken at the time of reviewing.

## Alternatives
### [Validator.js](https://github.com/chriso/validator.js)
Validator.js has a great range of validation rules available.
The library is a simple and non-intrusive with a straight forward API.
Pros:
* Every rule is its own function.
* API is simple to understand and use.
Cons worth noting:
* We will need more of our own code to test each field - unable to test multiple rules at once, and each rule is a function call.
* Extensible in the sense you can plug in more functions to the API, not provided by the library.

### [Valid.js](https://github.com/dleitee/valid.js)
Valid.js has a nice concept of validation rules as objects.
The library is non-intrusive and with a unique API.
Pros:
* Each rule will have its own validation object.
* API is simple to use.
Cons worth noting:
* Tests all rules and returns a boolean as a result, could run each rule individually to get atomic information about failure for messages.
* Creating so many objects could lead to performance hits for large forms, although theoretically it'd have to be closer to a thousand of validation rules potentially.

**Comment by chillu** [comment]
Oh my - written a long response, then closed the browser window... in short: ApproveJS is *very* young and unknown (300 monthly NPM downloads vs. 1,400,000 on validator.js). It's more constrained in scope, 44kb vs. 266kb source for validator.js. And overall its not a lot of code. So even if the library goes unmaintained in 2018, we could self-maintain it while managing a transition. It also doesn't try to solve client-side value sanitisation like validator.js, which I'd consider scope creep. So I'm fine with ApproveJS :)

**Comment by tractorcow** [comment]
My investigation into Approve.js also reveals they have very lax validation for things such as dates, based on regexp rather than real date validation. I think it's fine to allow development to progress, but I think either of the other two would be better long term.

**Comment by tractorcow** [comment]
I've done some work adding validation to the php form schema https://github.com/open-sausages/silverstripe-framework/commits/pulls/4.0/schema-validation-rules

**Comment by flamerohr** [comment]
Pull request created https://github.com/silverstripe/silverstripe-framework/pull/6251

**Comment by tractorcow** [comment]
Reviewing now. :D

**Comment by tractorcow** [comment]
Review done; Fixes requested. :)

**Comment by flamerohr** [comment]
We had found some limitations with Approve.js which wouldn't be ideal (displaying all error messages when only some of them apply and Date validation is rigid and relies on a set format).

I had looked into Valid.js and this also had a similar issue with dates.

We'll switch to Validator.js and see how this goes.
