### ISSUE TITLE
Implement a React form library 

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5524]
PRs:

 * https://github.com/silverstripe/silverstripe-framework/pull/6172
 * https://github.com/silverstripe/silverstripe-asset-admin/pull/287

Acceptance criteria

 * Any forms using FormBuilder will use the new library
 * Form functionality in campaigns and assets are operational using the new library
 * Form data can be loaded, edited, saved
 * Negligible performance regression, e.g. during typing
 * High-level use of the new APIs documented (it's fine to cross-link to other people's docs)

Excluded

 * Validation

----

Some options: https://react.rocks/tag/Form and https://react.rocks/tag/FormGenerator.

 * Compatible with Redux state management
 * Integrates well with the existing `<FormBuilder>` components and the SS form schema
 * Supports creation of custom form fields through `<FormBuilder>`
 * Stores form state separately from client-side models (Redux state tree)
 * Can optionally "bind" form state to client-side models
 * Allows customisation of form behaviour through JS (most likely a layer we need to add on top of a library)
 * Has performant input processing on complex reducer structures and large forms (this might be a blocker for redux forms, see [article about it's performance issues](http://www.position-absolute.com/javascript/my-controlled-input-dilemma-with-react-redux/)). Update: Known [workaround](https://github.com/erikras/redux-form/issues/454#issuecomment-166448837) is a onChange debounce with `setState` on the component.

Legacy cross-ref (for SilverStripe internal only, sorry): https://silverstripe.atlassian.net/browse/OSS-1804

## Tasks

 * [x] Update react to v15.0
 * [x] Pull in Redux Form dependency
 * [x] Set up Redux Form reducer
 * [x] `FormBuilder` to create `reduxForm` with `props.fields` required for Redux Form
 * [x] Set unique form name for Redux Reducer (based on "action" attr?)
 * [x] Set `initialValues` from form schema data
 * [x] Use `onSubmit` (to give form a chance to handle validation)
 * [x] Set button loading state based on `submitting` redux state from React forms (how to determine which button?)
 * [x] ~~Override `getFormState()` with `deep-freeze` behaviour~~ redux-form prefers ImmutableJS, but that's a larger library choice which we shouldn't just introduce here. Given that we've reduced the redraws, it's no longer a high priority for this use case.
 * [x] ~~Initialise form fields with `{...myFieldName}` prop expansion (automatically sets `value`, `required` and other HTML attrs)~~ Merging for now, which keeps the responsibility of deciding which props are actual DOM attrs with the component itself (rather than the data flowing through it) - so the status quo.
 * [x] Update schema after submit
 * [x] Update state after submit
 * [x] Remove structural fields from form data
 * [x] Graceful server error handling (unset loading state)
 * [x] Fix unit tests
 * [x] Fix documentation
 * [x] Fix createFn()
 * [x] Rebase and split up to logical commits
 * [x] IE10 testing
 * [x] Fix "flash of initial values" on submit
 * [x] Tabs switches in the navbar, but does not switch content
 * [x] `HtmlReadonlyField` shows no content (screenshot in comments below)
 * [x] CheckboxSetField doesn't have values (see https://github.com/silverstripe/silverstripe-frameworktest/pull/25)
 * [x] OptionsetField and CheckboxSetField cannot change value.

## Related

 * Implement client-side validation feedback: https://github.com/silverstripe/silverstripe-framework/issues/5523
 * Implement server-side validation feedback: https://github.com/silverstripe/silverstripe-framework/issues/5522
 * Use form builder to create form: https://github.com/silverstripe/silverstripe-asset-admin/issues/171

**Comment by micmania1** [comment]
I've been playing with http://redux-form.com/5.2.5/ lately. I'm not sure how that fits with the SS4 forms but might be worth a look.

**Comment by chillu** [comment]
Thanks @micmania1 it's on our radar already (preferred option, but haven't looked very deeply) :) So you like it?

**Comment by micmania1** [comment]
I haven't had enough experience to really give an opinion, but so far it seems pretty easy to use and extend. The API is very much like form controls in Angular 2 so Id say its on the right track and will at least have some familiarity for people who are used to Angular 2.

**Comment by chillu** [comment]
Updated react via https://github.com/silverstripe/silverstripe-framework/pull/5942 and
https://github.com/silverstripe/silverstripe-asset-admin/pull/242

**Comment by chillu** [comment]
Started at https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/redux-form

**Comment by dhensby** [comment]
I hear really good things about https://github.com/davidkpiano/react-redux-form

Apparently a great package and Redux-Form is not so great in terms of customisation, docs and clarity.

Here's a comparison: https://davidkpiano.github.io/react-redux-form/docs/guides/compare-redux-form.html

Pros for RRF:
- Boiler plate: minimal
- Customisation: Super simple
- Docs: Well maintained
- And is just overall insanely clean

**Comment by davidkpiano** [comment]
👋 Hey, I was pointed here by @tomspeak and am happy to help! I created React Redux Form and use it in numerous production projects, so I'm interested in solving bugs and accommodating complex use cases as fast as possible.

By the way -

> Negligible performance regression, e.g. during typing

The best performance enhancement for this is setting `updateOn="blur"` for any performance-sensitive fields (or all fields, haha):

```jsx
<Control.text model="foo.bar" updateOn="blur" />
```

(which is difficult to do in Redux Form). I am currently writing docs on tips for performance.

**Comment by chillu** [comment]
@dhensby Sorry for not responding earlier on `react-redux-form`, even though it was 8 days ago I was in the middle of the `redux-form` implementation already. I won't pretend to have evaluated every detail on why we chose one library over the other. At some point you just have to stick with something, otherwise you'll go insane in the current JS ecosystem. So in this case, we're sticking with `redux-forms`, unless somebody makes a compelling case and writes the PR to change it over. On quick review of `react-redux-form`, the model binding looks interesting, and `onBlur` rendering would be a nice performance enhancement - I think we get most of the benefits from simply using controlled fields in `redux-form` though (rather than re-rendering the entire form like in v5). The slightly reduced boilerplate when writing fields is not really relevant to our use case, given that most fields will be created programmatically through a JSON schema. `redux-form` has 4x the amount of contributors/stars/forks ... unfortunately a craptonne of open/closed bugs. So no clear winner, which makes "the working implementation" (in SilverStripe) the default choice :)

**Comment by dhensby** [comment]
Hey @chillu, the problem we have is we are making decisions on libraries without actually having production experience under our belt. Where we lack this experience we should be listening to those who have it and consulting with a wider community of experts rather than going off of number of stars or forks (which probably correlates more with project age than quality). 

Of course if we have invested time in a solution I'm not advocating throwing that away if there's a lack of clear benefit, so I agree we shouldn't start this over but I have heard from peers that these two libraries are oranges and apples in terms of quality, support and usability.

**Comment by chillu** [comment]
Yep, this RFC has been sitting here since May, and has been clearly visible in the Github milestones as upcoming work. So ample time for anybody interested to weigh in :) I'm not going out of my way to start a discussion about every development aspect on the mailinglist though, because it'd mean we never finish SS4. In previous tricky spots (like react-router), I've drawn on known React guys in the community like Aaron and Stevie by `@mentioning` them

**Comment by flamerohr** [comment]
`HtmlReadonlyField` is no longer showing content:
![screen shot 2016-10-13 at 10 29 03 am](https://cloud.githubusercontent.com/assets/1064889/19328493/5982755a-9130-11e6-9349-a970d75239a7.png)

**Comment by stevie-mayhew** [comment]
FWIW we use redux forms in production on all of our current sites. The latest version has it quirks but there hasn't been a situation that has dramatically effected our productivity or caused major bugs / headaches. We're looking actively at `react-redux-form` for a current project but at the moment have no absolutely compelling reason to switch.

**Comment by flamerohr** [comment]
`CheckboxSetField` doesn't have values or update with values.
`OptionsetField` cannot change value.

**Comment by chillu** [comment]
Can be tested through `frameworktest` with https://github.com/silverstripe/silverstripe-frameworktest/pull/25

**Comment by tractorcow** [comment]
@flamerohr said he'd reviewed this and it's ready to merge. Tomorrow I'll review and merge if possible. :)

**Comment by tractorcow** [comment]
Closed with https://github.com/silverstripe/silverstripe-framework/pull/6172
