### ISSUE TITLE
"More options" pop-over in React Bootstrap

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5611]
A pop-over is required for the "More Options" action which will be used within AssetAdmin and Pages but should be built in a way which if flexible to be used for other purposes. e.g. for help text.

To validate the feature, put the unpublish action into the file "More Options" section. 

https://projects.invisionapp.com/boards/9GX68PTXUQFH#/1547737/71700348

The more-options button is already in the template—just remove the class .hidden-xs-up from the button for it to show.

# Tasks

 * [x] Ensure that react-bootstrap has implemented popover for v4
 * [x] Review Paul's existing CSS work (https://github.com/silverstripe/silverstripe-framework/pull/5415)
 * [x] Styling
 * [x] Incorporate react-bootstrap v4 into build
 * [x] Form builder support for nested fields and actions (CompositeField, FieldGroup, TabSet)
 * [x] Decide on collision detection (via Tether?) or hardcode to right align Bootstrap popover, see http://v4-alpha.getbootstrap.com/components/popovers/
 * [ ] Merge https://github.com/silverstripe/silverstripe-framework/pull/5776

-- split from here

Moved to https://github.com/silverstripe/silverstripe-asset-admin/issues/169

 * [ ] Implement unpublish action on "File" section (no indication in UI at the moment)
 * [ ] Remove unpublish action when file is already unpublished

**Comment by tractorcow** [comment]
I've implemented some very basic nested form-schema for a custom dropdown container.

![image](https://cloud.githubusercontent.com/assets/936064/16440995/b6386d68-3e1a-11e6-9a50-66711029398c.png)

**Comment by clarkepaul** [comment]
I've added some styling so that the contents of the popup looks somewhat as it should.
@tractorcow I don't think the popup should be named based on form-actions as it should be able to contain any type of content (eg, help information).

It looks as though Tether is not working as it should for the positioning of the popup.

**Comment by clarkepaul** [comment]
@tractorcow do you think it makes sense to have both Bootstrap popovers as well as React-bootstrap popovers? Then we have a choice as to which we use, like non-react areas.

**Comment by tractorcow** [comment]
@clarkepaul react-bootstrap is just over the top of bootstrap right? So it's not really either or, but we use both.

Tether is working, but react-bootstrap doesn't support auto positioning.

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-framework/pull/5776

**Comment by sminnee** [comment]
I've merged this now.
