### ISSUE TITLE
Customise form presentation and behaviour in React

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#5630]
## Overview

This is a crucial step in convincing the community that the Form Schema approach actually holds up, and there's value in using React in this way to allow better CMS interfaces. Without this, it's actually easier to modify presentation and behaviour in SS3, because of Entwine's structure (easier to "override"). By default, a React view is closed off to customisations, for better or worse.

## Acceptance Criteria

 * Developers have a clear API for customising forms through FormBuilder
 * Developers can understand the relationship between FormBuilder and Redux Forms
 * Developers can target injector customisation by context (e.g. `TextField.AssetAdmin.EditForm`)
 * Developers can target injector customisation by partial context with wildcards (e.g. `TextField.*.EditForm`)
 * At least three common customisations are documented as a recipe
 * The following use cases are made possible through the API. This can be demonstrated by sample code and recipes rather than full implementations.
   * Toggle a form field based on input in other fields (in a form identified by it's `name` attribute)
   * Add a new form field at a specific position (through JavaScript)
   * Globally replace a form field type (e.g. `TextField`) with a more specific one (e.g. `CharacterCountTextField`) in all forms
   * Show a validation error with a message composed from other input
   * Change a "delete" button into a "confirm/cancel" button group on click (like [betterbuttons](https://github.com/unclecheese/silverstripe-gridfield-betterbuttons))

## Notes

Likely requires JS Dependency Injection to be sorted first through #4887 and https://github.com/silverstripe/silverstripe-framework/issues/6807.

Note that silverstripe-zenvalidator has found a good middle ground to avoid devs needing to customise form field behaviour too deeply by adding a richer declarative API to the PHP form fields: https://github.com/sheadawson/silverstripe-zenvalidator. This isn't a replacement for this card, but can help to guide the effort.

## Tasks (TBD)
- [x] Add context to Injector
  - [x] `Injector.get()` can specify dot-notated service names
  - [x] `Injector.transform()` Can apply HOCs to all, some, or a single context using wildcards
- [x] Update `FormBuilder` to accept an arbitrary form ID or name as part of its public API as a supplement to `schemaUrl`.
- [x] Update `FormBuilder` to use injected services as middleware in front of the `redux-forms` reducer
- [x] Create POCs
  - [x] A dropdown for Country that exposes State when set to USA
  - [x] A field that takes on a green border when another field is greater than a given value
  - [x] Given a PhoneNumber field, break up the field into three separate boxes (3 digits each) and have it save state to the original singular field
  - [x] Throw validation error if Country == USA and postal code length != 5 
  - [x] Have a delete button show a "confirm" state via a button group, like betterbuttons
- [x] Write documentation
  - [x] Update React DI docs to cover context
  - [x] Overview of API
  - [x] Recipes (e.g. for POCs)
- [x] Merge with Chris' work

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-admin/pull/112
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/506
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1860
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/30
- [x] https://github.com/silverstripe/webpack-config/pull/5
- [x] https://github.com/silverstripe/silverstripe-admin/pull/119

Note: Docs are rolled into the Redux PR at https://github.com/silverstripe/silverstripe-framework/pull/7042

##  POCs
https://github.com/open-sausages/experimental-react-di/blob/master/js/src/main.js

**Comment by sminnee** [comment]
@chillu I couldn't tell if this is type/docs or type/enhancement...

**Comment by sminnee** [comment]
@chillu I'm going to assume that this card is focused on writing docs or a tutorial about the above. There may be a PR or two to smooth the path but if major new architecture is required it's covered by cards such as #4887.

**Comment by chillu** [comment]
That's an accurate assessment - we might need some extension points, but other than the injector logic no major refactor should be needed.

**Comment by chillu** [comment]
Types of customisation:
 - Custom validation (e.g. based on other form input)
 - Custom parsing and formatting (e.g. DateField showing localised formats)
 - Custom presentation (e.g. conditional view for dependant dropdowns, replacement of field component)

Levels of customisation:
  - Apply to every form field of a certain type. Example: Timezone aware DateField
  - Apply to every form. Example: Phrase blacklisting through validation on all text input fields
  - Apply to every form managing a certain object. Example: Image licensing dialogs
  - Apply to forms for a certain page type. Example: RedirectorPage checks validity of redirection URL client-side.

Status quo:
- `<FormBuilder>` has an optional `createFn` prop which can be used to influence the creation of the inner form field component (`<Field component>`, e.g. `<DateField>`).
- There is currently no way to influence creation of the outer redux-form `<Field>` (hardcoded in `mapFieldsToComponents()`)
- Most logic needs to be applied to the outer redux-form component, only basics are passed through to the inner component (`value`, `onChange`, etc)
- `<FormBuilder>` has built-in aliases for validation defined in form schema JSON (e.g. `min/max`, `required`), which are resolved to JS inside the FormBuilder class
- Custom logic such as `parse()` or `validate()` can only be applied by a subclass of `<FormBuilder>` (and replacing the `mapFieldsToComponents()` implementation)

Potential improvements:
- `<FormBuilder>` could be replaced globally via dependency injection
- `<FormBuilder>` could be replaced locally via dependency injection (by specific service names, such as "FormBuilder.AssetAdmin.EditForm".
- We could add a callback prop for modifying the outer redux-form `<Field>` props to `<FormBuilder>`. That would require changing its instantiation code, or adding props in a subclassed constructor. It would also make it impossible for field components to determine their own non-trivial logic (such as `DateField` using `parse()` to convert between localised and ISO date formats).
- We could create a `<FormBuilder>` register for middleware-style callbacks, or generally just a collection of callbacks to apply to various aspects. Alternatively we could create HOCs for FormBuilder and all fields, but that seems to lend itself to crazy HOC nestings due to the unconditional application (10+ HOCs around a field wouldn't be unusual..)

Sketch of a form builder registry:

```js
class FormBuilderRegistry {


	
	/**
	 * Alter props for the outer form field component.
	 * Apply custom validation and parsing here.
	 * 
	 * @param {String} id Identifier for this rule
	 * @param {Object} previousProps Original props
	 * @param {Array} componentTypes Optional React component names to limit application. Example: [DateField,TimeField,DatetimeField]
	 * @param {Number} priority Higher priority means applied later
	 * @return {Object} previousProps Altered props
	 */
	updateComponentPropsFn(id, previousProps, componentTypes, priority);

	/**
	 * Alter props for the inner form field component.
	 * Presentational component, does not concern itself with validation or value parsing.
	 * 
	 * @param {String} id ...
	 * @param {Object} previousProps ...
	 * @param {Array} componentTypes ...
	 * @param {Number} priority ...
	 * @return {Object} previousProps Altered props
	 */
	updateFieldPropsFn(id, previousProps, componentTypes, priority);

	/**
	 * Adds a validation to one or more form fields
	 * 
	 * @param {String} id ...
	 * @param {Function} Arguments: name, value, formValues. Return: {valid: Boolean, message: String}
	 * @param {Array} componentTypes ...
	 * @param {Number} priority ...
	 */
	addComponentValidation(id, fn, componentTypes, priority);

	/**
	 * Adds validation to one or more forms.
	 */
	addFormValidation(id, fn, forms, priority)

}
```

**Comment by sminnee** [comment]
Would a more "javascripty" way of handling the registry be through a more open-ended callback than special methods for validation/props/etc/? So it's just passed an object-graph and returns an updated version of that object graph? It could follow the same design as a redux reducer, for example.

**Comment by chillu** [comment]
Additional use case to sanity check approach against: https://github.com/silverstripe/silverstripe-asset-admin/issues/310

**Comment by chillu** [comment]
Added the following two ACs after clarifying with @unclecheese that he left out this work from https://github.com/silverstripe/silverstripe-framework/issues/6807, and was happy to do it as part of this card:

 * Developers can target injector customisation by context (e.g. `TextField.AssetAdmin.EditForm`)
 * Developers can target injector customisation by partial context with wildcards (e.g. `TextField.*.EditForm`)

**Comment by unclecheese** [comment]
Here's my initial proposal for adding middleware to redux forms. To be clear, "middleware" isn't really an appropriate term here, because what you'd be registering is a specific function that gets passed the relevant slices of the form state and schema and passes them back to a single form reducer middleware to apply the transformation.

_lib/addFormMiddleware.js_
```js
const addFormMiddleware = (Original) => (state, action) => {
  if (action.meta && action.meta.form) {
    const { form } = action.meta;
    const middleware = Injector.get(
      'FormMiddleware', // This would always be the same. Helper method, maybe? Injector.getForm()? 
      form // the form name is your context. e.g. "AssetAdmin.EditForm"
    );
    if (middleware) {
      const updates = middleware({
        values: getFormValues(form, state),
        initialValues: getInitialValues(form, state),
        fields: getFormMeta(form, state),
        schema: state.schemas[form]
      });
      const updatedState = updates.state;
      const updatedSchema = updates.schema;
      const newState = {
        ...state,
        form: {
          ...state.form,
          [form]: {
            ...state.form[form],
            ...updatedState
          }
        },
        schemas: {
          ...state.schemas,
          [form]: {
            ...updatedSchema
          }
        }
      };
      
      return Original(updatedState, action);
    }
  }
  return Original(state, action);
};
```

_boot/index.js_
```js
reducerRegister.add('form', addFormMiddleware(ReduxFormReducer));
```

_my-module/main.js_
```js
Injector.transform('my-transform', (update) => {
  // again, since the FormMiddleware is constant, this could be a helper method (updater.form())?
  update('FormMiddleware.AssetAdmin.*', (state, schema) => {
    return {
       state: {
          ...state,
          values: {
            state.values,
            MyDateField: state.values.MyDateField.format('Ymd')
          } 
       }
    }
  })
});
```
