### ISSUE TITLE
Re-code i18n keys to have namespaces

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#5758]
## Acceptance criteria

 * [x] silverstripe-upgrader will replace classnames in strings in _t() calls
 * [x] Existing translations are migrated in transifex

See https://github.com/silverstripe/silverstripe-framework/issues/6726 for work to split the translation keys into the correct module.

----

## PRs

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/38
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6834
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/444
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1802
 - [x]  https://github.com/silverstripe/silverstripe-campaign-admin/pull/11
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6852
 - [x] https://github.com/silverstripe/cow/pull/49
 - [x] https://github.com/silverstripe/silverstripe-admin/pull/48

----

## Tasks

 - [x] Remove `.tx` from 3.x branches (all) in preparation for localisation freeze
 
Rest of tasks are 4.x:
 
 - [x] Update locale localisations (4.x) with `tx pull -a -s -f` to ensure we have current localisations from transifex.
 - [x] Run i18nTextCollector on all core modules (4.x) with merge DISABLED `?merge=false` to clear legacy strings.
 - [x] Run [upgrader](https://github.com/silverstripe/silverstripe-upgrader) with `--rule=lang` to update localisations.
 - [x] Check en.yml for un-upgraded strings (e.g. 'Permissions') and add these to the `.upgrade.yml` for the parent module ('Permissions' => 'SilverStripe\Security\Permission'). Then re-run the upgrader again.
 - [x] Manually upgrade all i18n API calls in *.js files (since upgrader can't rewrite these) (Use `ModuleName.ENTITY` convention, e.g. `AssetAdmin.FOLDER_NAME`)
 - [x] Check en.js for un-upgraded strings. Manually upgrade these (more searching and replacing in *.js files).
 - [x] Double check that all localisation files (yml and js, both source and non-en files) have been upgraded, and then install the [transifex client](https://docs.transifex.com/client/introduction). Get auth details from Damian. Push up all files for all modules (one at a time) to transifex with `tx push -s -f && tx push -t -f`. (push localisations, sources, and force).

---
From Ingo's comments on #5734:

Ingo: i18nTextCollector will collect fully qualified "namespaces" through DataObject->provideI18nEntities() now (for {$this->class}.SINGULARNAME. Is it too hacky to use DataObject::$table_name for it, assuming that core classes will get a short table name?

Sam: Can we do some kind of extract-transform-load step with transifex as a one-off?

Ingo: Yeah. It's also going to mess with everybody else's translations though (not just core), so ideally it's an optional part of the upgrader. Using <MyModel>.SINGULARNAME will be quite common in projects, because the key is generated by default on text collection. Or more explicitly mentioned in the upgrade guide as a manual task.

---

**Comment by tractorcow** [comment]
As a part of this we'll need to create a new set of transifex masters for 4.x going forward (the same as what we did for blog 2.0), to prevent 3.x strings getting messed up.

This should be done later on once we've completed namespacing.

My ideal is to keep using FQN for keys, and not use table_name, since we avoid conflicts in that case.

**Comment by chillu** [comment]
We can't duplicate transifex masters, as that'll put too much strain on the free resources we get from them. So we'll need a cut-off point where we no longer download new translations into 3.x, at which point we can change the location and key naming of the existing master files.

We'll also need to review which module translation keys belong to. In particular for JS, we now have keys in `framework` which should be in `admin`. And there's some really outdated ones in there, like `FileIframeField`

**Comment by chillu** [comment]
Assuming you mean "forking" in Transifex, it's still going to tax our free (or heavily discounted) resources there. Since probably 70% of the keys and translations are in the core modules. I don't think the benefit of having new translations in a late-stage release (3.x) warrants the additional complexity here.

**Comment by tractorcow** [comment]
Then let's freeze 3.x localisations, and simply switch over the current master keys for 4.x namespace / compatibility. All that's necessary is to remove the `.tx` folder from all 3.x branches. Sound good?

**Comment by tractorcow** [comment]
@ingo responding to your comment

> Ingo: i18nTextCollector will collect fully qualified "namespaces" through DataObject->provideI18nEntities() now (for {$this->class}.SINGULARNAME. Is it too hacky to use DataObject::$table_name for it, assuming that core classes will get a short table name?

I've updatde i18nTextCollector to support `__CLASS__` in string concatenations. You don't need to use providei18nEntities anymore.

**Comment by unclecheese** [comment]
Moving this to blocked, as I'm waiting on @tractorcow to update the upgrader to ignore JS per https://github.com/silverstripe/silverstripe-upgrader/issues/28

**Comment by sminnee** [comment]
@unclecheese merged the upgrader change
