### ISSUE TITLE
ModelAdmin, usability issue with search filters applied

### ISSUE THREAD

**Issue by colintucker** [silverstripe/silverstripe-framework#5871]
Since ModelAdmin was revised to have the search filter form appear by sliding down from the top, there doesn't seem to be any obvious way to indicate to the user that a filter is currently active.  After clicking "Apply Filter", the ModelAdmin interface refreshes (via GET) and once again the search filter form is collapsed.  I'd imagine this may be confusing for some users, who may switch to other tabs, attend to other tasks etc., then come back to the CMS without realising there is a filter currently active.

I think it makes sense for the search filter form to collapse after applying the filter and showing the filtered results, but perhaps a class could be applied to the GridField or the EditForm, e.g. `filter-applied`, that would allow a visual indicator that a filter is currently active on the results?  Or perhaps, a class applied to the `filters-button` in the top right of ModelAdmin to show that a filter has been applied?  Thoughts?

# AC
* Search results to show a notification which indicates what has been searched using the field label and keywords for each field eg Label:Keyword(s)
* Remove/hide modalAdmin actions (these could differ for different modalAdmins)
![pasted_image_18_07_17__11_08_am](https://user-images.githubusercontent.com/555033/28293691-8cfaaf5c-6ba9-11e7-99d3-dc15e79f363e.png)
* Ability to clear the search/filter

# Tasks
* [x] Show notification that the user is viewing search results, and what they have searched for
* [x] Add Clear search button

# Excluded
At some stage, the search field should be updated to match the files are and new pattern for pages (move search field to top right corner of UI)

# Related
https://github.com/silverstripe/silverstripe-cms/issues/632
https://github.com/silverstripe/silverstripe-cms/issues/1891

# Design: 
https://invis.io/EMCL4D6AY#/243734503_ModelAdmin_-_Search

# Pull requests
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7209
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/172

**Comment by tractorcow** [comment]
@clarkepaul how do you feel about a "filter active" indicator on the model admin sections?

**Comment by clarkepaul** [comment]
Yeah that is a huge UX failure. I would replicate the pattern from pages as much as possible. The message could be integrated into the same position as where the filter would have previously been, allowing the user to amend or clear filter.

Having the search fullwidth at the top was actually a bit of a temporary thing, the direction for the UX of the search and filter panel will look more like this https://projects.invisionapp.com/boards/FAX68PE52Y8W/ but that doesn't really concern the issue mentioned above. 

There still needs to be a indication the filter has been applied, as per pages area or as you have mention @colintucker.
![pasted_image_12_08_16__4_30_pm](https://cloud.githubusercontent.com/assets/555033/17612801/311e36e6-60aa-11e6-9ed3-790ff46047bb.png)

**Comment by tractorcow** [comment]
Given that this "bug" involves designing something that doesn't exist, I'm re-marking this as an enhancement.

**Comment by newleeland** [comment]
We done some rethinking around how the search mechanics worked, in regards to user experience. Using the selected colour state ($brand-primary: #29abe2;) to give a visual cue when "search mode" is active and inactive. Prototype: https://invis.io/VYBT5JOBM#/234846520_Home

**Comment by clarkepaul** [comment]
Please note that mockup uses a much older version of the CMS so the filter bar is black when opened. These are the visual changes from what I can tell according to that mockup are:
  * Filter bar changes colour to blue when filters are set
  * The background of contents of the gridfield turns light blue when a filter is set
  * The contents of the column which has been filtered uses bold text rather than a normal body weight

**Comment by lerni** [comment]
@clarkepaul @colintucker CSV-Import is also hard to find. And if you import, the Success Message like "Imported 20 records." gets hidden in the collapsed Search, since "Import from CSV" collapses Search Panel.

**Comment by clarkepaul** [comment]
@lerni that would be more relevant on this issue https://github.com/silverstripe/silverstripe-framework/issues/6431 

I will put a comment form you there.

**Comment by colintucker** [comment]
Thanks for your efforts with this @clarkepaul - the current filter/import stuff in `ModelAdmin` is usually the only thing clients complain about to me in the admin.  😉

**Comment by chillu** [comment]
Agreed this is high priority. Note that I'm also keen to make this "advanced filter" part of GridField components eventually, so it can be applied to any GridField. So ideally we find a design solution where the active filter indication is part of the GridField (e.g. also works if the GridField is halfway down a "edit page" form with other form fields). Maybe that's too much of a compromise, but just keep reusability in mind, and try to minimise the design variations between different uses of GridField. ModelAdmin is really just a glorified GridField. 

This is the current view searching for a page called "Home". It's not ideal either, doesn't indicate what search filters are applied, or how to find out more (search icon is very separate from the "showing search results" indicator).

![image](https://user-images.githubusercontent.com/111025/28040623-7c7d7950-661a-11e7-9b62-8a7420672538.png)


> We done some rethinking around how the search mechanics worked

@newleeland The mockup you linked to shows the inline search for GridField (on column headers). That's different from the ModelAdmin filters, which are a dedicated search panel. This issue is about ModelAdmin search, not about the inlined GridField search.

@clarkepaul Moving this to blocked until there's a design

**Comment by clarkepaul** [comment]
Jared had done a mockup above, but it's with V3 so would be good to update. His mockup https://invis.io/VYBT5JOBM#/234846520_Home

**Comment by clarkepaul** [comment]
We have been through this for the Files area (with the same/similar issues) but Pages is still using the old style search area and should be updated to the newer one which is present after searching.
<img width="736" alt="pasted_image_13_07_17__11_36_am" src="https://user-images.githubusercontent.com/555033/28144501-f5225a8c-67bf-11e7-9918-e7d7a1b2534e.png">

I propose we don't replace the actual search box in areas other than Files (as part of this issue) but improve some of the other differences like "Search results with TERM" and colours etc.

**Comment by clarkepaul** [comment]
@chillu seeing as the Pages doesn't have any React yet, is it too early to open an issue to update its search/filters to the newer pattern pictured above from the files area? 

We could show more of the filters applied in the notice also e.g. Search results with keywords “xxx”, with page type “xxx”, and with the status of “xxx”. were applicable.

**Comment by chillu** [comment]
Yep, the UX should be consistent with the "Files" area, and agree that adjusting the "Pages" area is out of scope - I've created a separate card for it: https://github.com/silverstripe/silverstripe-cms/issues/1891

**Comment by clarkepaul** [comment]
ModalAdmin search should model itself as much on Pages search results designs in https://github.com/silverstripe/silverstripe-cms/issues/632 (mockup https://invis.io/EACM3LEHK#/244049027_Pages_Search_Results_3_Results).

**Comment by unclecheese** [comment]
@clarkepaul @newleeland Can you confirm what you want for the variables in the template `You searched for [Keywords]: Mobil, [Category]: Telecommunications`? It looks like it should be the label of the form element, and the value provided. The form element label might be a bit more verbose than needed, e.g. "`Keywords (feel free enter multiple words separated by spaces)`". Using the `name` attribute of the form element is equally problematic. That may not be semantic at all. 

For the values, a dropdown or checkbox selection like`Category` is likely to be an ID, so we'll need a way of resolving search params to a human-readable label.

**Comment by clarkepaul** [comment]
Sorry that first field should read "Name:Mobil" not Keywords:Mobil because for the Modaladmin filters there isn't a generic overall search keyword which searches over all of the columns (to my knowledge).

**Comment by tractorcow** [comment]
Ok, fixed!
