### ISSUE TITLE
New UX insert link dialog - design and external URLs

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#5947]
## Acceptance criteria

* Links can be created through TinyMCE to the following:
  * An email address
  * An external URL
* Users can add link descriptions to all media types

## Exclusions

- Users do not have the ability to edit linked file descriptions from the insert link modal

## Tasks
* [x] Create user flow designs for each link scenario
* [x] Team/community feedback
* [x] Create email address FormFactory
* [x] Create external address FormFactory
* [x] Create email address plugin for TinyMCE with entwine component
* [x] Create external address plugin for TInyMCE with entwine component
* [x] Unit tests
* [x] Documentation
* [x] Behat tests

# Stories (for implementation) 

- [ ] https://github.com/silverstripe/silverstripe-framework/issues/6740
- [ ] https://github.com/silverstripe/silverstripe-framework/issues/6743
- [ ] https://github.com/silverstripe/silverstripe-framework/issues/6141

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/33 (and associated pull requests)
- [x] https://github.com/silverstripe/silverstripe-admin/pull/58
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/467
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1815
- [x] https://github.com/silverstripe/silverstripe-framework/pull/6893
- [x] https://github.com/silverstripe/silverstripe-framework/pull/6914

## Design
https://invis.io/BGAYOTRFY#/224873109_Insert_Link

## History

<details>

Suggested UX:
![insert-link](https://cloud.githubusercontent.com/assets/555033/18234725/043dd59e-7362-11e6-8265-a582fb70337b.png)

I think we could improve the UX of the Insert Link process by not nesting anchor links within the "Add page link" label. Adding links to a page is the most common action and by adding additional anchor fields in the mix (which aren't very intuitive) causes an unnecessary obstacle for authors.

If we slightly changed the label "Link to an anchor on this page" to "Link to anchor on a page", allowing user to choose the page first and then the anchor (defaulting to the current page), I'm pretty sure we can improve its intuitiveness. 

I've actually witnessed a new user trying to figure out what a anchor link was because they thought the fields need to be filed out in order to link to a page. There is also no link to help text for those who are unsure of what to do.
</details>

**Comment by SpiritLevel** [comment]
How about "Link to a page anchor on this site" or "Link to an anchor within
a page on this site" rather than "Link to an anchor within a page" ? I like
the first one best :)
And, perhaps it could be put right underneath the "Link to a page on this
site" option so the two are juxtaposed for quick comparison ?  You could
also put the tip beside the anchor option instead of beside the drop-down
with a title "What is a page anchor?".....just ideas to consider :)

**Comment by clarkepaul** [comment]
Good suggestions there. There also could be a possibility to just have a sentence about using anchors directly above the fields instead of tooltip. I also added a # as it is not explained if it is required or not and placeholder text as that field isn't explained.

I like "Link to a page anchor on this site" too.

**Comment by SpiritLevel** [comment]
And, maybe there is scope for a "Link to page anchor on another site" as
well ? Your sentence about anchors would then apply to both internal and
external sites. Tricky to get a nice consistent look and experience in all
this :)

One last idea, expanding on what you already have:

In Step 1, only have "Link to page on this site" and "Link to page on
another site" options, which would keep the number of step 1 options nice
and small. Then, if either of these page options are selected, an
additional option appears in Step 2 to enable users to indicate if they
want to link to an anchor or not. If they don't choose the anchor option in
step 2, then, in cases of pages on this site, offer a drop down, while, in
cases of external sites, offer a place to enter a URL. If they do choose
the anchor option in step 2, then provide a place to enter the anchor like
you already have, which looks like it would work for either internal or
external pages :)

Right...enough suggestions from me in the peanut gallery!

**Comment by clarkepaul** [comment]
Ha, yeah that would work if we include anchor links on other sites, makes it more consistent. Either way there are improvements to be made.

**Comment by clarkepaul** [comment]
Found a really old ticket which outlines the same improvements https://github.com/silverstripe/silverstripe-cms/issues/643

**Comment by clarkepaul** [comment]
More recent wireframes (actually design will need improvements etc icons). Essentially there is a dropdown in TinyMCE for selecting the type of link, the files link opens the insert file modal but the rest of the links (page, URL, email) open the same modal with a different tabbed section showing.
![image](https://cloud.githubusercontent.com/assets/555033/20548607/d31345a6-b189-11e6-9c62-5e9481d9b2f5.png)

I decided to not have a separate section for anchor links but to incorporate it into the "link to page" as suggested by @SpiritLevel. "Add anchor" can be an additional option on both internal page and external link.

**Comment by clarkepaul** [comment]
WIP Progress of design can be seen here https://invis.io/BGAYOTRFY#/224873109_Insert_Link

**Comment by chillu** [comment]
@tractorcow @clarkepaul @flamerohr I've created a follow up task about caching the "insert link" forms for less perceived delays in the CMS: https://github.com/silverstripe/silverstripe-admin/issues/71
