### ISSUE TITLE
Introduce asset permission model

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6063]
## Acceptance criteria

 * "Viewers" and "Editors" are properties on Folder and Files, with the default to inherit from parent, just like Pages
 * These fields appear on the folder/file detail froms
 * Default canView() and canEdit() implementations make use of these
 * 100,000 files, 1,000 per folder, are supported
 * For debate: should we use new SiteConfig fields for root permission or separate fields for pages and files?
 * Files with canView() = false for the current user aren't displayed in asset admin
 * Files with canEdit() = false for the current user show a readonly from in asset admin

Assumption: existing level of optimisation in `SiteTree::batch_permission_check()` is sufficient.

## Tasks

 - [x] Implement abstract hierarchal permission calculator based on current SiteTree permissions
 - [x] Update SiteTree to use new permission model
 - [x] Update File to use this permission module
 - [x] Update SiteTree unit tests
 - [x] Permission model unit tests
 - [x] Asset admin behat tests for permissions / readonly
 - [x] Verify NFR (100,000 files, 1,000 folders)
 - [x] Ensure readonly mode is visible in the asset-admin
 - [x] Ensure view / editor groups are editable within the asset edit form for files and folders
 - [x] Ensure that multi-select of groups can be done in react (upgrade or create new react component).
 
# Pull Requests

- [x] https://github.com/silverstripe/silverstripe-framework/pull/6877
- [x] https://github.com/silverstripe/silverstripe-assets/pull/13
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1811
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/465
- [x] https://github.com/silverstripe/silverstripe-admin/pull/54
- [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/57

----

Right now asset-admin is built to respect `canView()` and `canEdit()` permissions of files, however there is no default permission model provided.

We should have some permission model built in that allows protected files and folders, similar in concept to the default page permissions.

We may wish to make this functionality provided-by-default but able-to-be-removed, so that developers can replace the default scheme in its entirety with something else.

**Comment by tractorcow** [comment]
👍 

Something like an extremely bare-bones secureassets would be nice.

**Comment by chillu** [comment]
We're doing group selection via a simple CheckboxSetField for now, since that already exists as a React component. To be replaced with a react-select based MultiSelectField React component in https://github.com/silverstripe/silverstripe-admin/issues/52

**Comment by tractorcow** [comment]
All tasks done, pull request coming later.

**Comment by tractorcow** [comment]
I'll rebase once i18n rewrite and behat fixes are merged and green.
