### ISSUE TITLE
Remove Object class.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6085]
The following are "soft" reserved words:
- resource (as of PHP 7)
- object (as of PHP 7)
- mixed (as of PHP 7)
- numeric (as of PHP 7)  

To improve the possibility of SS4 working with PHP8, we should remove use of the "object" class name.

Rather than re-name it I suggest we remove it entirely and shift its important features to a set of traits, such as Extensible (which already exists).

A common "god ancestor" is an antipattern we can move away from!

## Acceptance Criteria

 - Object class has been removed
 - All functionality covered by the Object class has been refactored as needed
 
## Tasks

 - [x] Replace `$this->class` calls with `static::class`
 - [x] Replace `$obj->class` calls with `get_class($obj)`
 - [x] Find replacement API for Object::add_extension() / Object::remove_extension()
 - [x] Remove object class
 - [x] Change Object extending classes to use one or more of Injectable, Configurable, or Extensible
 - [x] Fix tests
 - [x] Document upgrade path
 
## PRs

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/77
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/478
 - [x] https://github.com/silverstripe/silverstripe-assets/pull/22
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1825
 - [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/37
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/14
 
 Merge framework last
 
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6927

**Comment by sminnee** [comment]
`Object::create_from_string()` would need to be shifted elsewhere.

**Comment by tractorcow** [comment]
Could we move it to injector?

**Comment by sminnee** [comment]
Yeah that makes sense @tractorcow :)

**Comment by sminnee** [comment]
OK I've removed references to the things that we'd remove in cms, reports, siteconfig, and asset-admin, so this change can be made without needing a coordinated merge.

 * https://github.com/silverstripe/silverstripe-cms/pull/1634
 * https://github.com/silverstripe/silverstripe-cms/pull/1633
 * https://github.com/silverstripe/silverstripe-reports/pull/53

The changes are minor, which is encouraging with regards to upgrade pain caused by this change. Most of the tricky references to Object and its services occur within framework itself.

**Comment by sminnee** [comment]
The extensibility system is relying on static methods and properties defined within the Extensible trait and pulled into Object. If we remove Object these need to go else

I think the best approach is to introduce a new class `SilverStripe\Core\ClassExtender`, and work with instance methods on a singleton rather than static methods and properties.

So `SilverStripe\Core\Object::add_extension` becomes `SilverStripe\Core\ClassExtender::inst()->addExtension()`

👍  or 👎 ?

**Comment by tractorcow** [comment]
Why not flip it around, and put it on Extension?

```
MyExtension::add_to_object('SomeObjject')`
```

or

```
Extension::add_to_object('MyExtension', 'MyObject')`
```

**Comment by tractorcow** [comment]
Note for future peer review: There are places where $this->class is used that don't inherit from Object (E.g. Config_For_class). Careful when doing search and replace. :)

**Comment by tractorcow** [comment]
@sminnee I think you're right; By moving away from `static $classes_constructed` properties we can consolidate extension state into a single instance of an object.

**Comment by tractorcow** [comment]
I've examined the feasibility of @sminnee 's suggestion and I propose two alternatives:

 - Drop support for Object::add_extension() with no replacement. You have to call add_extension() directly on a class that uses the Extensible trait.
 - Add a ClassExtender() object as suggested above. Extensible::add_extension() will invoke this, but it can be invoked directly with a parent and extension class.
 
@ingo do you want to make the choice? I propose the second since it allows us to remove static properties from extensible, and it would not be a complex refactor.

**Comment by chillu** [comment]
It's not entirely clear to me how `ClassExtender` would work. Would it be a instance-level and singleton dependency of classes which implement `Extensible`? Would `addExtension()` take `$this` as an argument? The protected functions on `Extensible` should stay protected I think (e.g. `beforeExtending()`). How would that work when the logic is in a separate class?

Also, which class uses which trait in this new system? I've sketched up my guess below:

Before:

```
class Object (use Extensible, Injectable, Configurable)
class ViewableData extends Object
class DataObject extends ViewableData
```

After:

```
class ViewableData (use Configurable)
class DataObject extends ViewableData (use Extensible, Injectable)
```

**Comment by tractorcow** [comment]
> Would it be a instance-level and singleton dependency of classes which implement Extensible?

It would be accessed more like a singleton `ClassExtender::singleton()` (which uses Injector)

> Would addExtension() take $this as an argument?

It would take `static::class` as a first argument as it used to apply extensions to types, not specific instances.

> The protected functions on Extensible should stay protected I think (e.g. beforeExtending()) How would that work when the logic is in a separate class?

extends() and beforeExtending() would remain on Extensible trait. Only add_extension and remove_extension would be moved to the new class.

> Also, which class uses which trait in this new system? I've sketched up my guess below:

In most cases direct subclasses of Object would have all three. Looking at which traits can be dropped from each instance is a harder task.

**Comment by tractorcow** [comment]
It's ready to peer review!
