### ISSUE TITLE
Clean up `SilverStripe\Forms` classes

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6099]
## Acceptance criteria
- The form field classes are changed as described below:

Remove:
- `CreditCardField`
- `CountryDropdownField`
- `PhoneNumberField`: Too hard to localise properly, not used in core
- `MemberDatetimeOptionsetField`
- `InlineFormAction`: It basically never worked, because the URL it submits ajax requests to is `admin-custom`. It's easily implemented in custom code if required, and the whole approach will change through React anyway. See https://github.com/silverstripe/silverstripe-framework/issues/1512
- `ResetFormAction`: Can be done via attributes

Keep:
- `GroupedDropdownField`: It implements a HTML5 feature (`<optgroup>`)
- `ToggleCompositeField`: Used in `SiteTree` for metadata, probably best to leave this until we move that section to React
- ... all the others

 * Document removals in upgrading guide

## Tasks

 * [ ] https://github.com/silverstripe/silverstripe-framework/pull/6883
 * [x] https://github.com/silverstripe/silverstripe-cms/pull/1812
 * [x] https://github.com/silverstripe/silverstripe-admin/pull/57
 * [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/35
 * [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/35

**Comment by sminnee** [comment]
Seems reasonable to me!

**Comment by tractorcow** [comment]
InlineFormAction is used by translatable module; So it does work somehow!

**Comment by sminnee** [comment]
Not critical for the beta1 milestone

**Comment by chillu** [comment]
It's the last opportunity to do this for 4.x (API change), and a fairly small piece of work.

**Comment by chillu** [comment]
Removing this, as I don't see how it's three points. Will just do this myself in 30 mins :)

**Comment by chillu** [comment]
I've replaced `InlineFormAction` with `FormAction` in translatable on 3.x, and it works just as well.
See https://github.com/silverstripe/silverstripe-translatable/blob/00682aa7bc31d6dc7c2c51651c84b055924a229e/code/model/Translatable.php#L1093 and https://github.com/silverstripe/silverstripe-translatable/blob/00682aa7bc31d6dc7c2c51651c84b055924a229e/javascript/CMSMain.Translatable.js#L72

Note that https://github.com/silverstripe/silverstripe-userforms/blob/master/code/model/editableformfields/EditableCountryDropdownField.php needs to be removed as well, but I'm not going to start upgrading that module to master :)

**Comment by tractorcow** [comment]
All merged.
