### ISSUE TITLE
Investigate GraphQL

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6102]
Investigation of whether GraphQL is a viable way of providing data to the React UIs for 4.0.

(Ingo's working on this outside of open-sourcerers team time at the moment)
# Acceptance criteria:
- Mock-up implementation ready
- Pros / cons listed on this ticket
- Assessment of API impact—would it be possible in 4.1?
- Shared with silverstripe-committers and silverstripe-dev for review

# Tasks
- [x] RFC draft (reviewed by team)
- [x] RFC posted
- [x] Fix PoC (rebased on latest master)
- [x] Add mutation example to silverstripe-graphql README

**Comment by chillu** [comment]
RFC posted at https://github.com/silverstripe/silverstripe-framework/issues/6245
