### ISSUE TITLE
React form support for Date/Datetime fields

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6140]
## Acceptance criteria

 * Native HTML5 date field inserted into React forms where a formschema specifies a date field
 * Placeholder text is shown for non-compliant browsers
 * Placeholder text can be localised to the user's preferred date format – dd/mm/yyyy (using the browser or the member profile data can support this)

----

See https://github.com/silverstripe/silverstripe-framework/issues/5521 for context.
Preferrably while also removing the jQuery UI dependency (find a react-based date picker component)

## Tasks

- [x] Implement https://github.com/silverstripe/silverstripe-framework/issues/6626 (blocker)
- [x] investigate into date/time input native browser support
- [x] create date field component (include injector)
  - [x] update injector
  - [x] create react component
  - [x] write docs
  - [x] write tests
- [x] create time field component (include injector)
  - [x] update injector
  - [x] create react component
  - [x] write docs
  - [x] write tests
- [x] refactor back-end datetime field to not use date and time fields
  - [x] refactor
  - [x] update tests
  - [x] update changelogs
- [x] create datetime field component - single field (include injector)
  - [x] update injector
  - [x] create react component
  - [x] write docs
  - [x] write tests
- [x] Legacy (jQuery/entwine) field for date time input
---

## Pull request

- [x] https://github.com/silverstripe/silverstripe-framework/pull/6783
- [x] https://github.com/silverstripe/silverstripe-admin/pull/21
- [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/34

**Comment by chillu** [comment]
This should be extremely trivial if we use native browser functionality like suggested in https://github.com/silverstripe/silverstripe-framework/issues/6626

**Comment by chillu** [comment]
I've thought about this a bit more, and think we can create an acceptable user experience without pulling in a whole bunch of code for a date picker UI - I'm hoping to get rid of jQuery UI in the lifespan of 4.x.

Additional research:
- Current uses of jQuery UI: Non-React tabs, toggle fields. We've removed the need for jQuery UI Dialogs (all React now), and JSTree never needed it. It seems possible to phase out jQuery UI, unless we commit to it in 4.x through date polyfills. Changes to browser support would be considered an API breakages, so we're effectively supporting IE10 without HTML5 date support until 2020.
- With our current bundling strategy, 85% of HTML5 compatible browser will receive an extra 70kb of jQuery UI even though they don't need it. Splitting this out would require server-side user agent checks.
- There's an [ECMA Standard DateFormatter API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat), but it doesn't use ICU date/time placeholders
- There's no solid approach for parsing PHP's ICU dates in JavaScript (e.g. https://github.com/moment/moment/issues/2050)
- Polyfills not using jQuery UI (https://github.com/chemerisuk/better-dateinput-polyfill, https://github.com/brianblakely/nodep-date-input-polyfill) have more limited date localisations (<10 locales), but that's not really a large factor
- Polyfills not using jQuery UI are likely not accessible (WCAG), but users with screen readers aren't likely to use IE10/IE11
- The only jQuery UI based polyfill is five years old, single maintainer: https://github.com/jonstipe/date-polyfill. We might have to write our own one...
- Moment.js (without localisation) plus Modernizr is 20kb
- We probably need Moment.js for client-side localisation soon anyway (e.g. nicely formatted readonly dates in history views)

Suggested additional tasks:
- Use short date formats as fallback input (e.g. 31/12/2017, no spelled out month names)
- Use default PHP format for locale, no user selection or YAML config (format isn't configurable by user for HTML5 either)
- Convert PHP's ICU default localised date format to Moment.js format for a limited number of syntax (basically d/m/y order plus delimiter)
- Use a minimal Modernizr include to determine HTML5 support on client
- Use Moment.js to accept localised user input, and convert it to ISO date format in a hidden field (server doesn't need to do conversion)
- Set a placeholder with an unambiguous formatted string via JS ("Example: 31/12/2017")
- Validate user input through Moment.js
- Remove date/time format customisation in admin/myprofile: It no longer applies for a large amount of use cases (date fields for 85% of users on HTML5 browsers). It means readonly dates (e.g. page history view) will use the default for your locale, but that's acceptable. Admins could still override the locale format globally for all users through YAML config.

**Comment by sminnee** [comment]
@chillu @flamerohr @unclecheese who's able to review this?

**Comment by chillu** [comment]
I'm reviewing

**Comment by chillu** [comment]
Server-side min/max validation on `DateField` and `DatetimeField` currently shows with ISO date values rather than localised ones. That's hard to solve since the values are generated on the server, but in the HTML5 default case, the server doesn't handle localisation (it's left to the browser). While we could replicate date localisation through `Date.toLocaleString()`, it requires custom JavaScript that won't be (easily) available outside of the CMS (e.g. in custom project code). 

![image](https://cloud.githubusercontent.com/assets/111025/25478860/dfda721e-2b96-11e7-92e7-5adb2c569deb.png)

The broader solution for this is to enforce HTML5 client side validation, since that already has localised messages and formats for min/max validation errors built into the browser. They're currently ignored, which should be fixed with https://github.com/silverstripe/silverstripe-admin/issues/45. Once that's fixed, the server-side validation errors with ISO date formats should only show to users without HTML5 datefield capable browsers (IE11, Firefox). Given the date is still readable, that's an acceptable limitation.

**Comment by sminnee** [comment]
Maybe raise it as a separate bug without a milestone attached, @chillu?

**Comment by chillu** [comment]
@sminnee The separate bug is the https://github.com/silverstripe/silverstripe-admin/issues/45 card mentioned here. It's really the lack of client side HTML5 validation. 

> Once that's fixed, the server-side validation errors with ISO date formats should only show to users without HTML5 datefield capable browsers (IE11, Firefox). Given the date is still readable, that's an acceptable limitation.

I don't think we'll realistically get around to this any time soon, so am reluctant to create a bug for it. It's a problem that'll "fix itself" over time, by browsers supporting HTML5 date fields (in the case of FF), and by less people using IE11.

**Comment by sminnee** [comment]
Ok fair call
