### ISSUE TITLE
React form support for TreeDropdownField

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6141]
Notes:

 * Aaron has built a combobox like selector for folders that might be a good replacements for TreeDropdownField. We should investigate that.
 
# Acceptance Criteria

 - I have a control that allows me to select one item in a hierarchal list, in any react form
 - The field should allow me to filter data sets too large to render at once, via a text search feature.
 - The field should represent the tree structure of my data set visually (e.g. by breadcrumbs)
 - The field should allow me to identify autocomplete results even if they're deeply nested
 - The field needs to be accessible to screenreaders and keyboard navigable

Exclusions
 - Autocomplete performance doesn't need to be addressed; slow down the request-frequency for MVP. Create a new issue outlining what more is needed at the closure of this story
 - 3rd party libraries should be treated as internal APIs and allowed to change in minor releases; we don't need to lock in for 4 years

# Desirable features (if feasible)

 - The field should allow me to navigate through data sets too large to render at once, via hierarchal incremental loading of nested trees
 
# Subtasks

- [x] Ensure that nested form field urls work in react components https://github.com/silverstripe/silverstripe-cms/issues/1510
- [x] Enable namespaced i18n localisations https://github.com/silverstripe/silverstripe-framework/pull/6790
- [x] Update TreeDropdownField / Hierarchy so that it can output JSON instead of just JSON https://github.com/silverstripe/silverstripe-framework/pull/6792
- [x] Build TreeDropdownField react component:
  - [x] Import react-select and update select to use this
  - [x] Redux state for tree
  - [x] Build endpoint for loading tree / subtrees
  - [x] Dropdown breadcrumbs
  - [x] Tree navigation behaviour
  - [x] Save / Repopulate saved value from database
  - [x] JS tests
  - [x] Integrate with redux-forms
  - [x] ~~Implement search~~ Broken out to https://github.com/silverstripe/silverstripe-framework/issues/6842
  - [x] patch campaign admin https://github.com/silverstripe/silverstripe-campaign-admin/pull/12
  - [x] Merge admin changes https://github.com/silverstripe/silverstripe-admin/pull/42
  - [x] merge asset-admin changes https://github.com/silverstripe/silverstripe-asset-admin/pull/447
  - [x] merge framework changes https://github.com/silverstripe/silverstripe-framework/pull/6843

----

See https://github.com/silverstripe/silverstripe-framework/issues/5521 for context. Just convert the existing entwine component for now, replacing the whole tree component is too a more long-term issue.

See asset-admin folder selection designs at https://projects.invisionapp.com/d/main#/projects/boards/1547737/52137452

**Comment by sminnee** [comment]
Could be Pjax converted from Entwine to React. Doesn't need GraphQLization, form field actions will need support.

**Comment by clarkepaul** [comment]
A good test candidate for this issue would be the asset folder tree (potentially to be used as part of the folder edit details https://github.com/silverstripe/silverstripe-framework/issues/5627

**Comment by sminnee** [comment]
Another test candidate is insert internal link: #6740

**Comment by tractorcow** [comment]
Started working on this; I'm looking at the tree-manipulation code in core at the moment.

I've started by stripping out anything sitetree-specific out of admin and into cms module. Next candidate is hierarchy.

WIP: 
- https://github.com/open-sausages/silverstripe-cms/tree/pulls/4.0/tree-dropdown-react
- https://github.com/open-sausages/silverstripe-admin/tree/pulls/4.0/tree-dropdown-react
- https://github.com/open-sausages/silverstripe-framework/tree/pulls/4.0/tree-dropdown-react

**Comment by tractorcow** [comment]
Next challenge is to get form actions working in react; Will need to hack around the fact that react sections don't store current record ID in session (urls will need to be different). Might need to add a custom LeftAndMain endpoint for nested form actions (similar to `schema` action).

**Comment by tractorcow** [comment]
```php
'GET nestedactions/$FormName/$ItemID/$OtherItemID' => 'nestedactions'
```

For example

**Comment by tractorcow** [comment]
Thought about this while overseas. I think it's a good time to remove dependency on that extra session var, and try to fix it in the URL.

Related: https://github.com/silverstripe/silverstripe-cms/issues/1510

**Comment by chillu** [comment]
I'd prefer this over the `GET nestedactions/` approach, which seems hacky. I know many CMS authors will be very excited about fixing this for all forms, basically anybody collaborating with other CMS authors on GridFields is in a world of pain at the moment.

**Comment by tractorcow** [comment]
Yeah, I'm looking at this at the moment as a custom form route handler (LeftAndMain specific).

```
private static $url_handlers = [
        'GET schema/$FormName/$ItemID/$OtherItemID' => 'schema',
        'EditForm/$ID' => 'EditForm'
    ];
```

And then I build in a custom request handler for EditForm that posts back to the id-suffixed URL.

**Comment by tractorcow** [comment]
I've taken 5 points out of this story and put them into https://github.com/silverstripe/silverstripe-cms/issues/1510 as a dependency.

**Comment by tractorcow** [comment]
I've started an RFC for implementation direction planning at https://github.com/silverstripe/silverstripe-framework/issues/6794

**Comment by tractorcow** [comment]
Working (but slightly buggy) PoC:
 - https://github.com/open-sausages/silverstripe-framework/commits/pulls/4.0/tree-dropdown-react-2
 - https://github.com/open-sausages/silverstripe-admin/commits/pulls/4.0/tree-dropdown-react-2
 - https://github.com/open-sausages/silverstripe-asset-admin/commits/pulls/1.0/tree-dropdown-react-2

**Comment by flamerohr** [comment]
I've found that `http://ss4.dev/admin/campaigns/DetailEditForm/5/field/Test/tree?format=json` works fine, but omitting the ID doesn't `http://ss4.dev/admin/campaigns/DetailEditForm/field/Test/tree?format=json`

This would be able to work with create forms right? Currently, you'll need to create a whole URL-action for the create form to work around this.

**Comment by sminnee** [comment]
Is it _supposed_ to work the ID committed? That seems like an edge-case that we shouldn't make necessary.

**Comment by sminnee** [comment]
Specifically, the form-URL of the DetailEditForm should always have the ID embedded into it, even if it's included on a page URL that lacks the ID

**Comment by flamerohr** [comment]
I believe it is supposed to work with ID omitted, at least for the case of loading the Form for creating a new data object. (current behaviour in campaigns' `FormBuilderLoader`)

The FormURL doesn't necessarily need the ID embedded into it, and in the case of creating it's actually superfluous because there isn't an ID to begin with.

There are a few options available:
* A separate FormURL for cases of creating, making ID mandatory for the Edit form.
* Keep Edit form behaviour as is and when calling field actions, the client will need an ID injected in as placeholder such as `0`
* Make ID mandatory, even for create cases.
  * Make ID 0 as default
  * Make ID as the value `create`, though would mean mixing/convoluting the data type that ID receives.

I will open a separate issue for this discussion (ping @tractorcow), as I don't feel this issue should block the TreeDropdownField work.

**Comment by sminnee** [comment]
Yeah — it's probably more likely to be an issue with URL routing than TreeDropdownField.
