### ISSUE TITLE
Remove archived items from campaigns

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6258]
## Acceptance criteria:

 * When archiving a page that has been added to a campaign, show a warning message, "this will be removed from X campaigns"
 * At that time, remove the page from the given campaigns so it no longer shows up in the campaign detail view.

----

We need to come up with a pattern for how archived items (items archived outside of the campaign) are displayed in campaigns, there are a few options I see for how this could work:

1. Remove archived items from campaigns. (history becomes complicated)
2. Show archived items in campaigns but add an "Archived" tag. (adds campaign bloat)
3. Hide archived items and have an option to show archived items. (requires more UI actions)

My preference is opt. 1, especially if we can show in the history of the campaign items were archived and automatically removed.

Eventually there will be an option to archive items when the campaign is published but this should be managed separately.

---

## Tasks

- [x] Update warning message
- [x] Remove archived pages from campaigns

---

## Pull request
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1774
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/9

**Comment by sminnee** [comment]
Option 1 with 1 of 2 approaches:

 * When opening that campaign, say "an item has been archived" without details
 * When archiving the page, say "this will be removed from X campaigns"

**Comment by clarkepaul** [comment]
I think option 1. is a good first step (MVP) along with the notification.

**Comment by clarkepaul** [comment]
Suggested updates to alert text are as follows "Warning: This page and all of its child pages will be unpublished, removed from campaigns and sent to the archive.
Are you sure you want to archive this page and all pages beneath it?"
https://invis.io/5UB2EX59Y#/226150587_Notifications

**Comment by phalkunz** [comment]
@clarkepaul So there's no mention of "_x campaigns_" like @sminnee suggested?

**Comment by clarkepaul** [comment]
True, updated as that is nice to have that info. Hopefully it isn't hard to get that info.

**Comment by sminnee** [comment]
It would also be good if it only mentioned child pages when archiving  page that actually has children.

**Comment by clarkepaul** [comment]
Had a bit more of a thought about this, archiving a page can get quite complicated as you not only remove the page you are on from campaigns but all child pages and their associated files/linked items (which aren't being used in other parts of the campaign). I don't see the value in just communicating how many campaigns are effected by the one page, when there could also be other campaigns which are also effected by pages/files being removed.

I think its best to keep the message generic unless we can provide all the details which could get pretty crazy with edge cases (something for later on in the roadmap).

Proposed change:
"Warning: This page and all of its child pages will be unpublished. These pages will be removed from their associated campaigns along with their linked items (e.g. files) before being archived.

Are you sure you want to archive this page and all pages beneath it?"

**Comment by clarkepaul** [comment]
More discussion on this matter with @sminnee, we should ignore all linked items which are implicitly added to a campaign. Hence X stands for the total number of campaigns effected:
"Warning: This page and all of its child pages will be unpublished and automatically removed from X campaigns and sent to the archive.
Are you sure you want to proceed?"
