### ISSUE TITLE
Responsive CMS menu

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6267]
Note this issue is no.2 on the list below but also the central reference of the other responsive type issues for Beta1.

## WIP acceptance criteria
* All main ModalAdmins have access to the CMS menu and be able to select any section within the menu to navigate to it.
* Admin tabs should be visible and selectable in all views, even they break onto the next line.
* The viewport is not limited to a 720px min-width, but provide natural scaling.
* The CMS should be more accessible to users rather than more inhibiting 

## Recommendations for implementation in order of most important (up to 8pts worth)
1. [MERGED](https://github.com/silverstripe/silverstripe-admin/issues/100#issuecomment-306384071) Remove constrained viewport see issue https://github.com/silverstripe/silverstripe-admin/issues/100

2. [< 768px] In order for the CMS to be usable on smaller screen sizes, the main menu within the CMS will need to be collapsible to allow the main content panels to take pride of place. This will include:
    * Requires hamburger link to trigger the menu from first level Admin sections. Hamburger icon to flip out with X icon. See squeeze icon https://jonsuh.com/hamburgers/ or this annitmation https://codepen.io/clarkepaul/pen/qjEMWV but squeeze is set up to be more accessible.
    * Center site name on mobile (top of menu)
    * Menu should animate out from the hamburger area in the top left. 
    * Width of the menu should be 100% - 60px so the following CSS might be good to use, you can use platform.silverstripe.com for a very similar example. mockups marked with for Beta1 https://invis.io/V6BW0ZNFH#/235742840_Navigation_Mobile_Start [~3pt]
       * Width: calc(100% - 60px);
       * Margin-left: calc(-100% + 60px);
       * Position: relative;
    * [All screen sizes] Move logout icon to the right of the profile name and reduce its size slightly, a new icon takes the logout icon positioned on the left of the user's name. [~1pt]
    * Excludes: Moving the SilverStripe branding and help link in the menu (this will be a seperate issue, so there will be no branding at the moment)

3. Drop ModalAdmin tabs at smaller viewport sizes see https://github.com/silverstripe/silverstripe-admin/issues/99
4. More options dropdown see https://github.com/silverstripe/silverstripe-admin/issues/101
5. ModelAdmin toolbar actions to fall back to just icons for smaller screens see https://github.com/silverstripe/silverstripe-admin/issues/102

## Related issues if time permits
6. [< 768px] Reduce sort dropdown in assets to icon so that it fits on smaller screens. see https://github.com/silverstripe/silverstripe-asset-admin/issues/496 [1pt]

7. [< 768px] Add a publish button to draft preview so the user can publish directly after. see https://github.com/silverstripe/silverstripe-cms/issues/1843

8. Increase spacing of site tree items vertically to ensure clickability by fingers [3pt] see https://github.com/silverstripe/silverstripe-cms/issues/1832#issuecomment-303685283

9. [All sizes] Tabs to have an overflow dropdown when there isn't enough space. Responsive tabs see https://github.com/silverstripe/silverstripe-framework/issues/1943 [5pt]

10. [All sizes] The history section within Pages will not work on mobile in its current state. See https://github.com/silverstripe/silverstripe-cms/issues/1493  for a possible interaction [8pt]

11. [ All sizes] Move CMS help to new area within the main menu along with SilverStripe brand [add link] [3pt]

## Tasks

- [x] Hamburger button
- [x] Show / hide mobile menu
- [x] Menu transition
- [x] Clean up menu CSS
- [x] Make the menu scroll-able if not enough space
- [x] Layout
  - [x] Mobile menu width (100% - 60px)
  - [x] Move logout icon to the right of the profile name and reduce its size
  - [x] Profile button on the left in space of logout button
  - [x] Center site name on mobile (top of menu)
- [x] Accessibility checks
- [x] Click outside mobile menu should close it

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-admin/pull/105

**Comment by clarkepaul** [comment]
Need to update viewport as it is constrained to 720px:
Swap `<meta name="viewport" content="width=720, maximum-scale=1.0" />` for `<meta name="viewport" content="width=device-width, maximum-scale=1.0" />`

**Comment by chillu** [comment]
Related bugs on iOS: https://github.com/silverstripe/silverstripe-framework/issues/6139
