### ISSUE TITLE
Upgrade to latest bootstrap

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-framework#6380]
## Acceptance criteria

 * Update to bootstrap 4a6
 * Patch react-boostrap as needed to fulfil our requirements

----

There are a few classes which have changed throughout the alphas of Bootstrap.

I will add more as I find them:
.pull-xs-right is now .float-xs-right
.btn-danger-outline is now .btn-outline-danger (applies to all buttons)

## Tasks

 - [x] CMS and admin use bootstrap v4 latest version (at time of implementation)
 - [x] Upgrade react-bootstrap
 - [x] Visual comparison done using frameworktest module as base
 - [x] Address uglify / bootstrap / collapse.js / util.js issue (see below comment)
 
## PRs

- [x] https://github.com/open-sausages/react-bootstrap/pull/2
- [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/39
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7262
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1922
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/583
- [x] https://github.com/silverstripe/silverstripe-admin/pull/187
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/42

**Comment by chillu** [comment]
Upgrading notes: https://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/

**Comment by clarkepaul** [comment]
Nice ta

**Comment by chillu** [comment]
We're on 4.0.0-alpha.2 at the moment, which is nearly a year behind, so the following changelogs apply:

https://blog.getbootstrap.com/2016/07/27/bootstrap-4-alpha-3/
https://blog.getbootstrap.com/2016/09/05/bootstrap-4-alpha-4/
https://blog.getbootstrap.com/2016/10/19/bootstrap-4-alpha-5/
https://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/

This might also require an update of `react-bootstrap` - we're on 0.30.8 (March 2017), the latest is 0.31.0

**Comment by chillu** [comment]
From Paul on Slack: It’s not that important as far as I’m aware. As long as its done before stable.

**Comment by wildflower** [comment]
Will all the Form holders etc be changed as part of this issue?
https://v4-alpha.getbootstrap.com/components/forms/#checkboxes-and-radios
for example CheckboxField_holder.ss needs a tweak to put the $Field inside the Label element to match the bootstrap example.
I've placed an updated  CheckboxField_holder.ss into /mysite/code/templates/forms and done a /dev/build?flush=1 as a work around

**Comment by clarkepaul** [comment]
Checkboxes should already be inside the labels for SS4.
![pasted_image_15_06_17__3_00_pm](https://user-images.githubusercontent.com/555033/27163443-8e561dce-51db-11e7-9157-bbb1afa46cbb.png)
<img width="514" alt="pasted_image_15_06_17__3_01_pm" src="https://user-images.githubusercontent.com/555033/27163445-960771ee-51db-11e7-8ef4-13a6f1b614dd.png">

**Comment by tractorcow** [comment]
There exists a specific issue I would like @flamerohr to please help out with.

Our vendor.js builds collapse.js (which requires util.js) from bootstrap, which is exported as BootstrapCollapse.

This behaviour can be tested on the campaign admin section.

![image](https://user-images.githubusercontent.com/936064/29198606-b87433da-7e99-11e7-886f-8330489a224c.png)

I can use the `bootstrap/js/src/collapse.js` fine, but only in watch mode. You can also get it to build in production by manually disabling the uglify plugin in webpack-config, and removing the `-p` webpack flag in package.json, however @flamerohr suggests that is a risky way to get it working.

using `bootstrap/js/dist/collapse.js` can build it it fails with `cannot load Util` runtime error in campaign admin.

Including all of bootstrap/dist/bootstrap.js causes an invalid jquery error, which is hard to solve due to our outdated jquery verision, and in any case we don't want the entire library installed.

**Comment by flamerohr** [comment]
I will create a separate story for the `BootstrapCollapse` issue that @tractorcow has mentioned, as this is a legacy issue where bootstrap was plugged on top of React (which is in itself not ideal) and we should be looking at building the Collapse feature by using the one provided by `react-bootstrap`
