### ISSUE TITLE
Consistently reference injector services in config

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6642]
## Acceptance Criteria

 * As a SilverStripe developer, I can predict the config path of a value if I know the PHP class/interface it relates to 
 * As a SilverStripe developer, I can determine any naming changes from the upgrade guide
 * Where existing config keys are changed and match class names, the silverstripe/upgrader will automatically rewrite my YAML configurations

## Notes

 * YAML rewriting is [already implemented](https://github.com/silverstripe/silverstripe-upgrader/blob/master/src/UpgradeRule/YML/UpdateConfigClasses.php) in silverstripe/upgrader

## Background

At the moment we're using different ways to name injectable services:

- Short concrete class names without namespaces (`FormSchema`)
- FQCN of PHP interfaces (`SilverStripe\Control\Cookie_Backend`, `SilverStripe\Control\Email\Mailer`)
- Aliases without a direct corelation to a class (`FlysystemPublicAdapter`, `ErrorHandler`)

This will be confusing to SS devs, and make it harder to convince them that DI is a good idea in general.

@sminnee and @tractorcow think service names should be FQCN of PHP interfaces, which means creating those interfaces where they're missing.

Any `Injector::inst()` uses should refer to the FQCN through a `use` statement, combined with `::class`. Example:

```php
use SilverStripe\Assets\Storage\AssetStore;

$store = Injector::inst()->create(AssetStore::class);
```

## Exclusions

 * Create new PHP interfaces (use base classes if none exists)
 * Create service name aliases for FQCN
 * Change handling of dependencies as instance properties
 * Upgrader changes (relies on classname rename functionality in YAML)
 
# Tasks

 - [x] Upgrade YML files for each core module (including modules installed as a part of core tests such as testsession).
 - [x] Upgrade all references to named configs
 - [x] Ensure all renamed services are registered with `.upgrade.yml` and will be invoked via upgrader (exclusions pending).
 
# Pull Requests

Note: Merge in order for best results

 - [x] https://github.com/silverstripe/silverstripe-assets/pull/19
 - [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/157
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6916
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1821
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/477

**Comment by tractorcow** [comment]
To add to this ,where we need multiple named services based on a common interface we should be using `.` delimited suffixes. E.g. `SilverStripe\Control\Email\Mailer.testmailer`.
