### ISSUE TITLE
"Are you sure you wish to leave" on react forms (assets/campaign)

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6683]
## Acceptance criteria

 * When you make changes on the asset-admin forms (i.e. react-powered forms) and you navigate elsewhere, the system warns "are you sure you wish to lose your changes?" or similar
 * Change detection works on all the bundled field types

## Tasks

 * [x] Implement in frameworktest
 * [x] Test/fix all field types there
 * [x] Apply to asset-admin file-details / confirm it works magically
 * [x] If campaign-detail-edit has already been updated to use react forms (separate story) test/review that too

## Pull requests

 - [x] https://github.com/silverstripe/silverstripe-admin/pull/76

**Comment by tractorcow** [comment]
@phalkunz reviewed, assigned back to you. See https://github.com/silverstripe/silverstripe-admin/pull/76
