### ISSUE TITLE
Move translations into correct module

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6726]
## Acceptance criteria

 * All translation-strings are in a transifex project relating the the correct module

## Tasks

Replaces https://github.com/silverstripe/silverstripe-asset-admin/issues/239

 * Use silverstripe-upgrader to namespace the translaction keys (#5758)
 * Run text collection without merge on each core module, removing unused strings and creating new, accurate master files
 * Move cms translations into silverstripe/asset-admin
 * Move cms and framework translations into silverstripe/admin
 * Move framework translations into silverstripe/security-admin
 * Move framework translations into silverstripe/campaign-admin
 * Manually migrate JSON translations over (and regenerate "dist" files via `cow`)
 * Push new master files and translations into correct Transifex projects
 * Remove `.tx` folders from 3.x branches since we now only support 4.x
 * Ensure cow doesn't allow pulling translations for 3.x releases (since that'd remove existing translations)

Notes:

 * Applies to both JS and YAML translations.
 * Do this after [recoding i18n keys to have namespaces](https://github.com/silverstripe/silverstripe-framework/issues/5758).

Excludes consolidation of existing JSON keys into YAML for both client and server use because:

 * We can't inline all translations in the webpack build due to dist size
 * If we were to use translations interchangeably in JSON and YAML, we'd need to implement count-based translations (`_t('MyObject.PLURALS', 'An object|{count} objects', [ 'count' => $count ])`) and the Rails-style persistence format (http://guides.rubyonrails.org/i18n.html#pluralization)
 * Can't use https://webpack.js.org/plugins/i18n-webpack-plugin/ since it'd create dozens of dist files which we need to commit to the repo

Related issue on silverstripe/reports: https://github.com/silverstripe/silverstripe-reports/issues/9

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1814 (fixes below framework tests)
- [x] https://github.com/silverstripe/silverstripe-framework/pull/6870
- [x] https://github.com/silverstripe/silverstripe-admin/pull/50
- [x] https://github.com/silverstripe/silverstripe-reports/pull/69
- [x] https://github.com/silverstripe/silverstripe-cms/pull/1807
- [x] https://github.com/silverstripe/silverstripe-versioned/pull/11
- [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/56
- [x] https://github.com/silverstripe/silverstripe-assets/pull/12
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/15
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/457

**Comment by unclecheese** [comment]
Running this script to automate this: https://gist.github.com/unclecheese/98049424beda617222af35cefb8ccfbf

**Comment by tractorcow** [comment]
Some modules have keys that point to classes belonged to other modules, but those other modules never define those keys.

@unclecheese and I have agreed that we need to rename some keys, rather than simply move them across to modules. Below are the keys and suggested mappings:

Note that all renames are purely per-module, and should not be renamed globally.

cms keys:

- SilverStripe\Admin\CMSBatchAction: Split into:
  - SilverStripe\CMS\BatchActions\CMSBatchAction_Restore
  - SilverStripe\CMS\BatchActions\CMSBatchAction_Publish
  - SilverStripe\CMS\BatchActions\CMSBatchAction_Unpublish
- SilverStripe\Admin\LeftAndMain rename into SilverStripe\CMS\Controllers\CMSMain
- SilverStripe\AssetAdmin\Controller\AssetAdmin renamed into SilverStripe\CMS\Model\SiteTreeFileExtension
- SilverStripe\Reports\SideReport: Split into:
  - SilverStripe\CMS\Reports\BrokenRedirectorPagesReport
  - SilverStripe\CMS\Reports\BrokenFilesReport
  - SilverStripe\CMS\Reports\BrokenLinksReport
  - SilverStripe\CMS\Reports\BrokenVirtualPagesReport
  - SilverStripe\CMS\Reports\EmptyPagesReport
  - SilverStripe\CMS\Reports\RecentlyEditedReport

**Comment by tractorcow** [comment]
Finally done.
