### ISSUE TITLE
New UX insert link dialog - internal URLs

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6740]
## Acceptance criteria

 * Links to pages can be created through TinyMCE
 * Users can add link descriptions to all media types
 * When the cursor is on an existing internal page link, opening the "insert link" panel allows editing of the link
 * I can insert a link with a custom title set in the dialog when no selection is made
 * When editing an existing link, clearing the selection removes the link
 * I can explicitly remove a link from the dialog

## Tasks

* [x] Create Internal URL form in React
* [x] Create entwine script to inject in to tinymce
* [ ] Re-instate commented out behat tests

## Resources

 * Related ticket: #5947
 * Precondition: #6141 
 * Designs: https://projects.invisionapp.com/share/BGAYOTRFY#/screens/224873109

## Related

 * [Inline edit/remove of links in HTML editor](https://github.com/silverstripe/silverstripe-admin/issues/66)
 * [New UX insert link dialog - Insert anchors](https://github.com/silverstripe/silverstripe-admin/issues/65)

## Exclusions

- Create AnchorLink (dropdown list) component for the form, refer to `HTMLEditorField_Toolbar::getanchors()`
- Users do not have the ability to edit linked file descriptions from the insert link modal

## PRs:

 - [x] https://github.com/silverstripe/webpack-config/pull/2 (critical , please merge first and update NPM)
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/6969
 - [x] https://github.com/silverstripe/silverstripe-cms/pull/1834
 - [x] https://github.com/silverstripe/silverstripe-admin/pull/88
 - [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/491

**Comment by tractorcow** [comment]
WIP is at https://github.com/open-sausages/silverstripe-admin/tree/pulls/4.0/tinymce-link-dialog

I've dropped priority of this story in lieu of some confirmation with @sminnee

**Comment by clarkepaul** [comment]
I don't think this covers all of the dev from #5947 as it misses: link to file, link to email, and link to external url. @tractorcow is all of that work separated out into other issues?

**Comment by tractorcow** [comment]
Yes @sminnee split the work into separate stories.

**Comment by tractorcow** [comment]
See

-  https://github.com/silverstripe/silverstripe-framework/issues/6743
-  https://github.com/silverstripe/silverstripe-framework/issues/6740
-  https://github.com/silverstripe/silverstripe-framework/issues/6141

**Comment by chillu** [comment]
Changed ACs from:

 * Links can be created through TinyMCE to the following:
   * Pages
   * Anchor link on a page
* Users can add link descriptions to all media types
* Should be in CMS module

to

* Links to pages can be created through TinyMCE
* Users can add link descriptions to all media types
* The insertion is disabled when no selection is made
* When the cursor is on an existing internal page link, opening the "insert link" panel allows editing of the link
* When the cursor is on an external URL, file or email link, the "link" tinymce dropdown has only the relevant options enabled
* When editing an existing link, clearing the selection removes the link

**Comment by clarkepaul** [comment]
New acceptance criteria look good, @chillu it would be good to go over some of the UI next week to confirm some the designs and discuss edit functionality. Some of the mockups need a bit of talking to and then we can add a bit more acceptance criteria for editing.

**Comment by flamerohr** [comment]
Re-instate behat tests:
```
#  Scenario: I can link to an internal page
#    Given I select "awesome" in the "Content" HTML field
#    And I press the "Insert Link" HTML field button
#    When I select the "Link to a page on this site" radio button
#    And I fill in the "internal" dropdown with "Home"
#    And I fill in "my desc" for "Link description"
#    And I press the "Insert" button
#    # TODO Dynamic DB identifiers
#    Then the "Content" HTML field should contain "<a title="my desc" href="[sitetree_link,id=1]">awesome</a>"
#    # Required to avoid "unsaved changes" browser dialog
#    Then I press the "Save draft" button

#  Scenario: I can link to an anchor in an internal page
#    Given I select "awesome" in the "Content" HTML field
#    And I press the "Insert Link" HTML field button
#    And I select the "Link to a page on this site" radio button
#    And I fill in the "internal" dropdown with "Details"
#    And I select "youranchor" from "Form_EditorToolbarLinkForm_AnchorSelector"
#    And I press the "Insert" button
#    Then the "Content" HTML field should contain "<a href="[sitetree_link,id=3]#youranchor">awesome</a>"
#    # Required to avoid "unsaved changes" browser dialog
#    Then I press the "Save draft" button
```

**Comment by chillu** [comment]
After talking a bit more with @clarkepaul, I've removed the following ACs:

 * The insertion is disabled when no selection is made (replaced with: You can insert a link with a custom title set in the dialog when no selection is made)
 * When the cursor is on an external URL, file or email link, the "link" tinymce dropdown has only the relevant options enabled (too hard)

Added AC:

 * I can explicitly remove a link from the dialog

I've split out the anchor work into another card: https://github.com/silverstripe/silverstripe-admin/issues/65.

Created a new card for a "edit/remove link" overlay: https://github.com/silverstripe/silverstripe-admin/issues/66

**Comment by clarkepaul** [comment]
FYI I've updated the mockups to match new acceptance criteria.

**Comment by tractorcow** [comment]
WIP at https://github.com/open-sausages/silverstripe-admin/tree/pulls/4.0/insert-page-link

**Comment by tractorcow** [comment]
Prs created but need to fixup some tests. Monday....

**Comment by tractorcow** [comment]
for @clarkepaul here are some screenshots:

![image](https://cloud.githubusercontent.com/assets/936064/26534089/b1655ff6-4474-11e7-8c27-541ac4a61caf.png)

![image](https://cloud.githubusercontent.com/assets/936064/26534095/bb149c38-4474-11e7-9a16-2b346aba2e40.png)

**Comment by clarkepaul** [comment]
Sorry been away from computer most of the morning so couldn't provide feedback early enough, my only minor changes for this was the modal heading and link names in the dropdown being different from the designs. I will open a new issue for these here https://github.com/silverstripe/silverstripe-admin/issues/93
