### ISSUE TITLE
de-couple schema type and type attribute

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-framework#6741]
Currently, the "type" property for a field schema is defined for schema type use.
While at the same time, TextField uses that property to determine the "type" attribute it has.

Case in point, the SearchForm in asset-admin uses DateField `type = date` and that uses the TextField component.

This could lead to inconsistencies later down the line, such as if you want a "tel" type for the TextField it would require asking Injector to use the TextField for the type of define a custom component name to use.

## Tasks

- [x] Add `schemeType` and map the front end component
- [x] Update unit tests
- [x] Check that fields which require a type is still functioning (e.g. TextField, DateField)

## Pull requests

- [ ] https://github.com/silverstripe/silverstripe-framework/pull/6894
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/59

**Comment by mikenz** [comment]
https://github.com/silverstripe/silverstripe-asset-admin/blob/master/tests/php/Forms/UploadFieldTest.php#L60 will need to be updated for this too
