### ISSUE TITLE
New UX insert link dialog - file URLs

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-framework#6743]
## Acceptance criteria

 * Links can be created through TinyMCE to download a file (accepts all file types)
 * Users have a way to select a single file from all of the files presented in the files area
 * Users can use the search field to refine the selection of presented files
 * Users can add link descriptions to all media types and choose to open the file within a new tab/window if they decide to do so
 * Users have the ability to upload files prior to linking them through the UI (already developed)
 * The UI should resemble the same UI as what is available in the Files area (asset-admin module)

## Tasks
- [x] Split routing and formSchemaOverride logic from InsertMediaModal
- [x] Create file link form
- [x] Create entwine script to inject to tinymce
- [x] Re-instate behat tests

## Resources

 * Related ticket: #5947
 * Mockups: https://projects.invisionapp.com/share/BGAYOTRFY#/screens/224873109

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/94
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/493
- [ ] https://github.com/silverstripe/silverstripe-cms/pull/1839

**Comment by flamerohr** [comment]
Re-instate behat tests:
```
#  Scenario: I can link to a file
#    Given I select "awesome" in the "Content" HTML field
#    When I press the "Insert Link" HTML field button
#    When I select the "Link to download a file" radio button
#    And I fill in the "file" dropdown with "file1.jpg"
#    And I press the "Insert" button
#    Then the "Content" HTML field should contain "<a href="[file_link,id=1]">awesome</a>"
#    # Required to avoid "unsaved changes" browser dialog
#    Then I press the "Save draft" button
#    # Check that the field is reset when adding another new link
#    Given I select "content" in the "Content" HTML field
#    When I press the "Insert Link" HTML field button
#    Then I should not see a ".ss-uploadfield-files .ss-uploadfield-item" element

#  Scenario: I can link to an anchor
#    Given I fill in the "Content" HTML field with "<p>My awesome content<a name='myanchor'></a></p>"
#    And I select "awesome" in the "Content" HTML field
#    When I press the "Insert Link" HTML field button
#    When I select the "Link to an anchor on this page" radio button
#    And I select "myanchor" from "Form_EditorToolbarLinkForm_AnchorSelector"
#    And I press the "Insert" button
#    Then the "Content" HTML field should contain "<a href="#myanchor">awesome</a>"
#    # Required to avoid "unsaved changes" browser dialog
#    Then I press the "Save draft" button
```

**Comment by flamerohr** [comment]
https://github.com/silverstripe/silverstripe-admin/issues/93 has been fixed by the pull requests in this story

**Comment by tractorcow** [comment]
I'll peer review this tuesday.

**Comment by tractorcow** [comment]
Done!
