### ISSUE TITLE
Customise React components through injection

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#6807]
As a SilverStripe developer, I want to be able to add, remove, or modify behaviour, state, or UI
in the React-powered areas of admin so that I can customise the application via a module or
my project.

## Acceptance Criteria:

* Thirdparty developers have an accessible, easily-understood API for injecting their own components into the CMS UI
* CMS UI components can be overriden with customised replacements
* CMS UI components can be wrapped with Higher Order Components
* Clear, informative errors are thrown if a developer tries to modify behaviour after boot.
* The order in which customisations are applied is predictable and configurable
* The API for extending the UI, state, and functionality of the admin as it pertains to React components is well-documented, and the steps required to do so are explained in detail.
* Existing CMS React components use the DI solution
* The following use cases are made possible through the API. This can be demonstrated by sample code and recipes rather than full implementations.
  * Show the "last edited" date on a gallery tile (component composition)
  * Block opening the detail form of a gallery tile if the file is in draft mode (event overrides)

## Tasks:
- [x] Implement context-based DI layer described [here](https://github.com/krasimir/react-in-patterns/tree/master/patterns/dependency-injection)
- [x] Replace all existing calls to `Injector.js` with new context-based solution.
- [x] ~~Apply [BottleJS](https://github.com/young-steveo/bottlejs) DI library to context-based solution~~
- [x] Draft an API for an SS-specific wrapper around the DI layer, and get reviewed internally by at least two frontend developers
- [x] Create SS-specific wrapper for DI layer based on agreed-upon API
- [x] Develop several PoC implementations for injected components:
  - [x] Customise the title field of a `GalleryItem`
  - [x] Create two modules that customise `TextField` behaviour. One to log character count, and one to check password strength
  - [x] A core UI button that is customised to throw a `window.confirm` that if denied will kill its original action
- [x] Write documentation on how to use the aforementioned APIs.

## Related

 * [RFC-9: UI Extensibility](https://github.com/silverstripe/silverstripe-framework/issues/4887)

## Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-admin/pull/70
- [ ] https://github.com/silverstripe/silverstripe-asset-admin/pull/487
- [x] https://github.com/silverstripe/silverstripe-framework/pull/6957

## POCs
- https://github.com/open-sausages/experimental-react-di (Depends on [experimental asset-admin](https://github.com/open-sausages/silverstripe-asset-admin/tree/experimental/react-injection-POCs))

## Documentation
https://github.com/silverstripe/silverstripe-framework/pull/6957

**Comment by chillu** [comment]
Unsetting estimate, that should be done in backlog grooming by the whole team.

**Comment by chillu** [comment]
![image](https://cloud.githubusercontent.com/assets/111025/25160894/ee90d2ac-250c-11e7-9c66-25035c1d5d83.png)

Trying to figure out how much language expressiveness we give up by going to a DI container. Same issue as `Injector` in SilverStripe PHP really. While we don't need to implement Flow or Typescript right now, DI is going to be a big factor in how useful these language extensions will be to us going forward. In the screenshot above, you can see a component injected through BottleJS, which is explicitly typed to its original implementation (`MyComponent`). The downside here is that we need to use `import MyComponent` in addition to calling `bottle.container.MyComponent` wherever an injected service is used. I think that's an acceptable tradeoff for retaining expressiveness.

**Comment by chillu** [comment]
@steve-silverstripe As a core contributor with a lot of React experience, I'd be keen to hear your thoughts on this as well. There's "customise frontend" related cards which are linked in the sections of the main RFC at https://github.com/silverstripe/silverstripe-framework/issues/4887. This one is the basis for lots of this work: Customisation through dependency injection. Aaron is working on a PoC at the moment, which will go towards solidifying an API.

**Comment by unclecheese** [comment]
I've written up some documentation. https://github.com/open-sausages/experimental-react-di
