### ISSUE TITLE
Customise Redux state and actions 

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#6809]
## Acceptance Criteria

* The initial application state can be influenced
* The state tree can be extended
* Mutations of the application state can be intercepted
* New actions can be added to influence the state tree
* Clear, informative errors are thrown if a developer tries to modify behaviour after boot.
* The order in which customisations are applied is predictable and configurable
* The approach is well documented, with at least one recipe showing sample use cases
* The following use cases are made possible through the API. This can be demonstrated by sample code and recipes rather than full implementations.
  * Change the default sort of items in asset-admin
  * A new "select all" button selects all gallery items
  * When a file is selected, add it to the breadcrumbs

## Tasks

- [x] Refactor Injector Container, so it can be instantiated and behaviour customised if needed.
- [x] Migrate reducer registry to Injector (as a service `Injector.reducer`)
- [x] Create an API which allows developers to intercept/influence application state changes (the `*Reducer.js` files) and makes it easy for developers to inject their own reducer middleware
- [x] A way exposed to obtain/provide the global stored state for middleware, as they may need data from a different namespace.
- [x] Make sure initial state for the application can be influenced
- [x] Make sure actions in a reducer can be intercepted/blocked/modified
- [x] Throw errors (with clear messages) if trying to modify behaviour after boot
- [x] Document clear examples of how to approach this API
- [x] Unit tests for this API
- [x] Create POCs:
  - [x] Cancel showing badges when moving files to folders
  - [x] Change the preview image (in editor) to a placeholder image instead of the thumbnail
  - [x] Have breadcrumbs always have "Company logo" as the top-level first entry
    - Created middleware which renames "Files" breadcrumb to "Custom Files BUG", for fun :P
- [x] Reconcile with Aaron's customise form work closer to the end

*Excluded*
- Create actions registry to Injector
- Create an API which allows developers to intercept/influence state action change calls (the `*Action.js` files)
- POCs that can be done by middleware for the AssetAdmin or Gallery components, with a bit of sorting out the HOC orders.
  - Change the default sort of asset admin
  - "Select all" button for gallery items
  - When a file is selected, add it to breadcrumbs
  - A custom widget in the corner of the CMS that tracks how many files you've uploaded this session

## Notes

 * Depends on [Customise React components through injection](https://github.com/silverstripe/silverstripe-framework/issues/6807)
* Depends on the pull request here https://github.com/silverstripe/silverstripe-admin/pull/112

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/114
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/508
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/28
- [x] https://github.com/silverstripe/silverstripe-framework/pull/7042
 
## Branches WIP
- https://github.com/open-sausages/silverstripe-admin/tree/feature/its-not-reducering-the-injector
- https://github.com/open-sausages/silverstripe-asset-admin/tree/feature/its-not-reducering-the-injector
- https://github.com/open-sausages/silverstripe-campaign-admin/tree/feature/its-not-reducering-the-injector
- https://github.com/open-sausages/silverstripe-framework/tree/feature/its-not-reducering-the-injector

POC repo
- https://github.com/open-sausages/injected-redux-pocs

**Comment by sminnee** [comment]
Before we kick this off, I'd prefer to take the acceptance criteria and develop a customisation scenario that validates the list of hooks you've identified. Right now the AC are a little too much like a grab-bag of technical tasks—I couldn't see a non-Ingo picking this up and running with it. ;-)

**Comment by flamerohr** [comment]
So the idea I had come up with for redux state middleware is something like this:
```
// initial registering the reducer in silverstripe/module
Injector.reducer.register('breadcrumbs', BreadcrumbReducer);

// thirdparty who wants to inject middleware for, or even code after the above code
Injector.reducer.transform('breadcrumbs', MyModifyingReducer);
```

`MyModifyingReducer` would look very similar as a reducer:
```
/**
 * @param {object} state - should not have an "initialState" because the original reducer will run and return a state first anyway
 * @param {object} action - regular action object found in any other reducer
 */
function reducer(state, action) {
  switch (action.type) {
    case 'ACTION_MODIFIES_ORIGINAL':
      // this action exists in the original reducer, but you're making an extra change to it
      return deepFreeze(Object.assign({}, state, { KEY: action.payload * modifier }));

    case 'ACTION_IS_NEW':
      // this action does not exist in the original reducer, and it's like an extra "modification" or "addition" to the redux state
      return deepFreeze(Object.assign({}, state, action.payload));
  }

  return state;
}
```

So, the idea is Injector will register its own reducer function to redux, and it will call the registered reducer first then the sorted middleware afterwards - cascading the new state down the composed chain of middleware.

for the example above, it will look something like this in theory:
```
state = MyModifyingReducer(BreadcrumbReducer(state, action), action);
```

**Comment by unclecheese** [comment]
Looks good! The only sticking point for me is I'm unclear on why we need another API specifically for reducer registration. It seems to me we could use the existing top level Injector API to create higher-order reducers, so to speak.

```js
Injector.register('breadcrumbs', BreadcrumbsReducer);

const MyBreadcrumbsReducer = (BreadcrumbsReducer) => (state, action) {
  switch (action) {
    // break the middleware chain
    case 'SOME_ACTION':
      return { ...state, someNewAttribute: true };
    // keep the middleware chain
    case 'OTHER_ACTION':
      return BreadcrumbsReducer(
         { ...state, newProp: false },
         action
      );
    default:
      return BreadcrumbsReducer(state, action);
  }
}
```

If there's a legitimate case for reducers not being higher-order functions, I guess my question would be why don't we enhance components this way, too?

```js
component = MyCustomComponent(OriginalComponent(props), props));
```

Maybe I just need clarification on what makes reducers special in relation to components?

**Comment by flamerohr** [comment]
Another approach I had in mind is passing the previous "original" reducer as a callback, I preferred the method 1 above, but this one could also have its advantages (intercepting an ACTION for another, rare case and really weird imo)
I guess this one is open to all sorts of troubles, which is why I prefer the above, because it follows more closely to the paradigm which redux promotes.

so, to start off, the idea is still the same when defining:
```
// initial registering the reducer in silverstripe/module
Injector.reducer.register('breadcrumbs', BreadcrumbReducer);

// thirdparty who wants to inject middleware for, or even code after the above code
Injector.reducer.transform('breadcrumbs', MyModifyingReducer);
```

`MyModifyingReducer` would look different to normal a reducer:
```
/**
 * @param {object} state - should not have an "initialState" because the original reducer will run and return a state first anyway
 * @param {object} action - regular action object found in any other reducer
 * @param {function} originalCallback - Get the original transformations/newState before your own transformation, or set the new state/action before the original happens.
 */
function reducer(state, action, originalCallback) {
  switch (action.type) {
    case 'ACTION_CALLS_DIFFERENT_ORIGINAL_ACTION':
      // triggers the original reducer with a different action, for whatever reason you'd want to do this (e.g. Archive replacing Delete maybe?)
      return originalCallback(state, { type: 'DIFFERENT_ACTION', payload: { SOMETHING HERE } });

    case 'ACTION_MODIFIES_ORIGINAL_SLIGHTLY':
      // take the newState returned by the original and just tweak it a little to be more in favour for you
      return deepFreeze(Object.assign({}, originalCallback(state, action), { NEW MODIFICATIONS HERE }));

    case 'ACTION_IS_NEW':
      // this action does not exist in the original reducer, and it's like an extra "modification" or "addition" to the redux state
      return deepFreeze(Object.assign({}, state, action.payload));
  }

  return originalCallback(state, action);
}
```

**Comment by flamerohr** [comment]
> The only sticking point for me is I'm unclear on why we need another API specifically for reducer registration.
I guess I'm unclear on how to identify that the registered object/function is actually a the reducer.
As I need to define all reducers to redux quite close to the beginning of the booting process.

I guess the second idea I had was very similar to your's, except without the HOC wrapper function :)

**Comment by unclecheese** [comment]
Yeah, I like that. The second approach would require no new APIs or documentation. So I think from a PO standpoint the burden would fall on the first approach to sell its value. I'm not sure at this point I see that value, but I'm open to persuasion. :)

**Comment by flamerohr** [comment]
Actually, your HOC approach would be better than the second method I have because of `thunk`'s `withExtraArgument` API, which my approach would break.

**Comment by chillu** [comment]
I like Chris' last suggestion (`Injector.reducer.register('breadcrumbs', BreadcrumbReducer);`), since it means less API concepts to learn for devs. You could argue that we should move `Injector.register()` to `Injector.service.register()` then? Keep in mind that we'll also need to register GraphQL queries soon. Most of the time "service" will mean "component", but I think it'd be misleading to call it "component" all of the time. In DI speak, it's a "service".

The disadvantage of all approaches is that devs with existing knowledge in writing Redux reducers need to learn a slightly different API (call the original callback or the HOC), but that seems unavoidable if we want to retain full flexibility (cancel actions etc). It's a bit unfortunate that the [redux forms reducer plugins](http://redux-form.com/6.7.0/docs/api/ReducerPlugin.md/) work differently and don't allow invoking the `originalCallback` explicitly, but we shouldn't limit our API just because they did.

I'm not too keen on purposely making the API different from writing your own reducers though (rather than transformations on existing reducers). So if we're looking at something like [redux-actions](https://www.npmjs.com/package/redux-actions), we should use it everywhere.

I think Chris' last example code does a great job at communicating the possibilities already in terms of developer docs

I assume you're still working on an API to set the initial state?

**Comment by flamerohr** [comment]
Re: `Injector.service.register()`
---
I think this is worth exploring as we will have more services later, and we'd need to distinguish whether it's for redux, or graphql, or react components, or whatever else we may extend.
An important case for redux (at least) is that I will need to a way to get all registered reducers to set into the redux store.

I actually didn't agree with how `redux-forms` enables users to plugin reducers because it's only for specific forms (rather than a generic reducer for all forms), my first example tries to follow the but without the limitation mentioned in `redux-forms`.
The drawback with the first example is that you have no way to intercept the actions coming through to prevent/block the original reducer from an action you're trying to modify (e.g. change delete to soft-delete)

**NOTE**
On that note about changing actions, I'd argue using the react component injector service to replace actions would be the better place to do it, rather than in the reducer. The reducer is about modifying the data in the store during an action - the action itself (e.g. a `fetch` called) would still happen and ping the server.

Re: initial state
---
Yeah, the second example enables us to set an initial state quite easily. Whereby the first example doesn't enable us to set the initialState very easily.

```
function reducer(state, action, originalCallback) {
  switch (action.type) {
    default:
      // first example of completely overriding the initialState, ignoring the original initialState
      if (typeof state === 'undefined' || typeof action.type === 'undefined') {
        return myModifiedInitialState;
      }
      // second example of overriding the initialState, but still retain the original initialState
      if (typeof state === 'undefined' || typeof action.type === 'undefined') {
        return Object.assign({}, originalCallback(state, action), initialState);
      }
  }

  return originalCallback(state, action);
}
```

Re: different APIs to reducer
---
I agree, I'm not too keen on purposely making the API different from writing your own reducer either... I'd like to keep something like [redux-actions](https://www.npmjs.com/package/redux-actions) out of this story, I think that's more for creating an action than for reducer anyway :)
My idea for that wasn't posted because I didn't believe that was the way to go.

**Comment by unclecheese** [comment]
The more I think about this, I really see no way around fragmenting `Injector` into multiple sub-APIs.  Here's what I would suggest:

```
Injector.service // generic DI middleware/factory creator

Injector.ui // or "component"... extension of service, only applies React specific stuff like displayName

Injector.reducer // see above

Injector.form // Form middleware is going to be fundamentally different than the standard reducers

Injector.query // TBD

Injector.mutation // TBD
```

**Comment by flamerohr** [comment]
yeah, I think fragmenting `Injector` into sub-APIs is the way to go, it's quite tricky to not have the segregation.
The other idea was to have a type param `Injector.register('breadcrumbs', BreadcrumbsReducer, { type: 'reducer' });` but this convolutes the API more than it helps...

**Comment by unclecheese** [comment]
Transforms _should_ be at the top level, but they don't need to be. From my perspective, it would just make things a lot easier for developers. It's the difference between this:

```
---
name: my-module
---
SomeObject:
  extensions: [Foo]
OtherObject:
  extensions: [Bar]
```

and

```
---
name: my-module-foo
---
SomeObject:
  extensions: [Foo]
---
name: my-module-bar
---
AnotherObject:
  extensions: [Bar]
```

Modules tend to do all this stuff in one group, and developers tend to want to override by module, not by concern.

**Comment by chillu** [comment]
> Create an API which allows developers to intercept/influence state action change calls (the *Action.js files)

Can you outline how you want to approach this? Assuming we want to keep action function definitions pretty simple, this would be a matter of how to handle the original callback in your reducer transformation? You can decide to run the original reducer callback before/after your transformation, or not at all. I'm doubtful if any more customisation is needed on the actions side (e.g. wrapping action calls in injectable methods when invoked in component logic). Example of what an action currently looks like in asset-admin:

```js
export function setFiles(fieldId, files) {
  return (dispatch) =>
    dispatch({
      type: ACTION_TYPES.UPLOADFIELD_SET_FILES,
      payload: { fieldId, files },
    });
}
```

**Comment by flamerohr** [comment]
True... I had forgotten all but one action had been stripped of their fetch calls, that was my main concern with injecting actions.

We can forget about this, given that the last fetch in an action is stripped out eventually (records actions?)
I think that's some old work anyway, they needs some TLC.
