### ISSUE TITLE
Implement recipe pattern for installer

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-framework#6860]
See https://github.com/silverstripe/silverstripe-framework/issues/5992

As a developer, I can start a SilverStripe project with sensible defaults and tailor them to my project's needs, while still being able to pull in upgrades.

## Acceptance Criteria

 - I can add a recipe to any project via `composer require <recipe>` and  it will setup any required project files (e.g. Page.php for cms, or per-recipe `mysite/_config/recipe.yml`)
 - The following recipes exist (replacing the `installer` project):
   - The current core release: framework, cms, assets, campaign, siteconfig, reports
   - A minimal framework-only project
 - A user can create a project based on a recipe, remove one of the recipe-provided packages, and still make upgrades to future releases of the recipe without automatically installing that package.
   - "Inlineable recipes" is most likely necessary to facilitate this
 - The approach is well documented (getting started guides, details on how to build recipes)
 - You can use recipes through `composer require` on a blank `composer init` (rather than `composer create-project`)
 - The installer project isn't broken

Nice to have / technical notes:

 - A recipe is not a module, and can only require other modules, or bootstrap the root project files.
 - There is minimal duplication between recipes; A core change (e.g. modifying a dependency constraint of silverstripe/config) should only need to be made in the core recipe.
 - A tool exists that will inline any recipe, adding it's dependencies to my root composer.json, allowing me to customise them after the fact.
   - A recipe exists that is a good starting point for new SilverStripe developers, including as well as core userforms, blog, and other modules tbc. This will most likely be used, e.g. for demo sites. *This may be split to a separate story*

## Tasks

 - [x] Implement composer plugin to handle bootstrapping of project files
 - [x] User documentation for using and creating custom recipes
 - [x] Implement silverstripe/recipe-framework for framework-only minimal install
 - [x] Implement silverstripe/recipe-cms for complete install
 - [x] ~~Update cow to produce and upload archives to ss.org for each recipe on release~~ Moved to https://github.com/silverstripe/cow/issues/54
 - [x] Implement "inline" feature
 - [x] Ensure that upgrade to new recipes works
 - [x] Ensure that a recipe can be removed
 - [ ] Ensure that all core recipes are tested via travis
 
Peer review tasks:

 - [x] https://github.com/silverstripe/recipe-plugin/issues/1 Please review code base
 - [x] https://github.com/silverstripe/recipe-plugin/pull/3 Implement deletable resource rule
 - [x] https://github.com/silverstripe/silverstripe-installer/pull/193 Installer PR

**Comment by sminnee** [comment]
> A recipe exists that will install all necessary testing tools (e.g. behat, phpunit) and .travis.yml uses this

Shouldn't we just use `require-dev` of the modules for this?

**Comment by tractorcow** [comment]
> I can use any recipe as a base via composer create-project and it will setup any required project files.

If using create-project, the files in root pretty much just stay there. that's all this means by "setup". :) Exactly how installer currently behaves.

> I think that cow should take a recipe name as an argument and not attempt to contain within it a canonical list of recipes.

If we group recipes we should be able to do a combined release if needed correct? case in point, we don't want a separate release plan for cwp-recipe-basic, cwp-recipe-blog, and cwp-installer. We release them as one "main" recipe with separate components we tag as a single action.

> Shouldn't we just use require-dev of the modules for this?

Since we are shifting to prefer-stable, we should prefer-stable for behat-extension, testsession, etc... rather than just dev.

> A user can create a project based on a recipe, remove one of the recipe-provided packages, and still make upgrades to future releases of the recipe without automatically installing that package.

I'm in favour of adding this to the A/C too.

**Comment by sminnee** [comment]
> I can use any recipe as a base via composer create-project and it will setup any required project files.
> If using create-project, the files in root pretty much just stay there. that's all this means by "setup". :) Exactly how installer currently behaves.

Yeah — this will mean that the content of recipe repos has to be limited to those files that would make sense as part of a new project. We've hit a number of points of conflict in relation to this; if this is the status-quo then I would suggest that we advise _against_ using recipes directly with create-project and instead recommend something else, such as:

     mkdir project 
     cd project
     composer init
     composer require some/recipe

**Comment by sminnee** [comment]
> Case in point, we don't want a separate release plan for cwp-recipe-basic, cwp-recipe-blog, and cwp-installer

A couple of points:

 * If you run cow on a parent recipe, having it run operations on all child recipes seems logical
 * I think that having 3 separate CWP recipes like this is a bit of an anti-pattern and a side-effect of us not having the recipe tooling discussed this project. I'd expect that instead we could just have 1 recipe and you could remove the pieces that you don't like.

**Comment by tractorcow** [comment]
> Alternatively, we could have a create-project base that is separate from the recipe.

This is probably the other way that we could go; Split projects (root) and recipes (dependencies) entirely, or only require one or the other.

> If you run cow on a parent recipe, having it run operations on all child recipes seems logical

Right. :)

> I think that having 3 separate CWP recipes like this is a bit of an anti-pattern and a side-effect of us not having the recipe tooling discussed this project. I'd expect that instead we could just have 1 recipe and you could remove the pieces that you don't like.

If we could make recipes composable and able to be inlined, we could merge recipe-basic and blog, as we no longer have the issue of removable modules. If that's the case, do you want to make inlineable recipes an A/C rather than a nice to have?

**Comment by tractorcow** [comment]
> We've hit a number of points of conflict in relation to this; if this is the status-quo then I would suggest that we advise against using recipes directly with create-project and instead recommend something else, such as:

> mkdir project 
> cd project
>  composer init
> composer require some/recipe
 

Thinking more about this, getting rid of "create-project" might be the way to go, and we instead get users to pull in recipes as dependencies: No more installer?

**Comment by sminnee** [comment]
> Thinking more about this, getting rid of "create-project" might be the way to go, and we instead get users to pull in recipes as dependencies: No more installer?

Let's get the recipe working without create-project first, and then review.

**Comment by chillu** [comment]
@tractorcow Sounds like a great idea, although I'm still working through it (lots to take in). For now, can you please make a case for why this needs to be in beta1, as opposed to later in the 4.0 release cycle? From my initial review, it doesn't look like it introduces API changes, just an alternative way of assembling project dependencies, correct? If we stop supporting the installer project for 4.0 final, that just affects new projects. Existing projects upgrading to 4.0 final will just need clear instructions for how their composer file should look like.

**Comment by tractorcow** [comment]
> For now, can you please make a case for why this needs to be in beta1, as opposed to later in the 4.0 release cycle? 

My expectation is that the initial version of the recipe system may have problems that come out of testing, which for many users won't be until a tag is made. We should want at least one level of separation (beta1 -> beta2) to iron out these issues before we stabilise the recipe API.

**Comment by tractorcow** [comment]
@chillu I've developed a proof of concept at https://github.com/tractorcow/recipe-cms (it's setup on packagist, so you can do a real-live install) if you want to see something tangible.

**Comment by chillu** [comment]
As discussed in our backlog planning, we can create a small beta3 release if you're concerned about beta2 being the first release where this approach is included - that doesn't make it beta1 material :)

**Comment by tractorcow** [comment]
Tasked!

**Comment by chillu** [comment]
HVe you seen symfony flex? http://fabien.potencier.org/symfony4-compose-applications.html

**Comment by tractorcow** [comment]
Wow looks like a really hot idea!

**Comment by sminnee** [comment]
It'll be worth keeping an eye on what they're doing for inspiration, although the specific quite highly 

Another data point is Drupal installation profiles such as Acquia Lightning: was well as bundles of modules, these have setup wizards.

**Comment by tractorcow** [comment]
I've got a minimal `composer require-recipe` working. At the moment it only allows you to install a new recipe, but we'll also get update working later.
![image](https://user-images.githubusercontent.com/936064/27944139-e30e1a9c-6338-11e7-9302-8f06bfc9e498.png)

![image](https://user-images.githubusercontent.com/936064/27944135-d7798842-6338-11e7-8d37-f0c8e247b5de.png)

**Comment by tractorcow** [comment]
Next week I'll work on `update-recipe`

**Comment by tractorcow** [comment]
ok, so these are the commands we'll probably have:

`require-recipe` add a new recipe and inline it. Fails if already installed.
`update-recipe` update an inlined recipe. If the dependency isn't inlined, it'll automatically inline it.

Removing a recipe would pretty much be pulling out the inlined depedencies you don't want....

How does this sound @sminnee ?

**Comment by sminnee** [comment]
Seems fine to me but I'd want a confirmation from @chillu :)

**Comment by tractorcow** [comment]
Please see https://github.com/tractorcow/recipe-plugin/issues/1 for peer review holder for plugin

**Comment by tractorcow** [comment]
Proof of concept at https://github.com/silverstripe/silverstripe-installer/pull/193

This is a big change! Please make sure to review.

**Comment by flamerohr** [comment]
have created https://github.com/silverstripe/silverstripe-framework/issues/7204 for the last task that couldn't be done until after all the merge happens.
