### ISSUE TITLE
Update tutorials in the Learn / Lessons section for SS4 compatability

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#7353]
Right now, all the lessons are written for 3.0. We'll need 4.0 compatible lessons in place before the stable release. Video is too time consuming to upload, so we'll just upgrade the text of the tutorials, and the code in the repository.

## Plan of attack

* Meet with Jared/Paul/Andy for a design strategy to satisfy all of the UI upgrades required in issues described on the one-ring-rentals repository. https://github.com/silverstripe/one-ring-rentals/issues

* Once designs are agreed on, a designer (looking like Andy would do this), will mock up the changes.

* During design, upgrades to text can start.

* Upgrades to code will be done from scratch on a new repository, e.g. `one-ring-rentals-4.0`. Although, this might present a good opportunity to use better semantics, e.g. `silverstripe-lessons-4.0`

* Approach to upgrades -- follow the tutorial like a user, make changes as needed to the code, and implement incrementally on a local install of the one-ring-rentals site to ensure accuracy.

* Give special attention to the comments/questions section. Many of the comments are useful feedback on pieces of information that were not described, or inaccurate. Many of the questions were never answered. Those should be used to improve the overall quality of the tutorials.

* Follow a comms plan approved by Nicole and/or Ingo on how to inform the community of these changes. Overall message -- 4.0 upgrades are currently a stopgap measure. Better videos and revamped lessons section is forthcoming.

## Estimated time required:

10-11 working days, spanning 11-14,  25-29 September, and 2 October
(9 days of text upgrades, 1 day of development, half a day of QA/promotion)

## Tasks
- [x] Upgrade lesson: "Up and running"
- [x] Upgrade lesson: "Creating your first theme"
- [x] Upgrade lesson: "Migrating static templates into your theme"
- [x] Upgrade lesson: "Adding dynamic content"
- [x] Upgrade lesson: "Working with multiple templates"
- [x] Upgrade lesson: "The holder/page pattern"
- [x] Upgrade lesson: "Adding custom fields to a page"
- [x] Upgrade lesson: "Working with files and images"
- [x] Upgrade lesson: "Introduction to the ORM"
- [x] Upgrade lesson: "Working with data relationships: has_many"
- [x] Upgrade lesson: "Working with data relationships: many_many"
- [x] Upgrade lesson: "Introduction to frontend forms"
- [x] Upgrade lesson: "DataExtensions and site config"
- [x] Upgrade lesson: "Introduction to ModelAdmin"
- [x] Upgrade lesson: "Controller actions / DataObjects as pages"
- [x] Upgrade lesson: "Building a search form"
- [x] Upgrade lesson: "Lists and pagination"
- [x] Upgrade lesson: "Ajax behaviour and ViewableData"
- [x] Upgrade lesson: "Dealing with arbitrary template data"
- [x] Upgrade lesson: "Creating filtered views"
- [x] Upgrade lesson: "Beyond the ORM: Custom SQL"
- [x] Upgrade lesson: "Advanced environment configuration"
- [x] Upgrade lesson: "Dependencies and modules"
- [x] Upgrade lesson: "Creating great open source modules"
- [x] Upgrade lesson: "Publishing your own module"
- [x] Development: Frontend work for new lessons UI
- [x] Development: Backend work for new lessons features (e.g. version tagging)

**Comment by chillu** [comment]
Lessons are added to https://github.com/open-sausages/silverstripe-lessons

**Comment by unclecheese** [comment]
Designs, approved by myself and @clarkepaul

![learn landing page](https://user-images.githubusercontent.com/654636/30937655-f12c4a90-a433-11e7-919a-c8e5fd76deff.png)

![article page 2](https://user-images.githubusercontent.com/654636/30937679-005cb158-a434-11e7-9228-4e614c578a4d.png)

**Comment by chillu** [comment]
Lookin' great overall! A few notes:

- Images are broken on 3.x lessons - is this a UAT only thing? If there's images missing, can we sync them from live to get an accurate preview? http://sssites-ssorg-uat.sites.silverstripe.com/learn/lessons/v3/up-and-running-setting-up-a-local-silverstripe-dev-environment
- The links to the next tutorials need to be relative to the current folder - e.g. on lesson 0, the link at the very bottom points to http://sssites-ssorg-uat.sites.silverstripe.com/learn/lessons/creating-your-first-theme, which auto-redirects to the current "stable" release (currently v3). 
- There seem to be broken links in v3 - the link at the bottom of lesson 0 links back to the landing page instead of the next tutorial. Maybe run a link checker through it?
- The Markdown is a bit off - maybe do a once over of the rendered version? E.g. "Let's test this..." paragraph on http://sssites-ssorg-uat.sites.silverstripe.com/learn/lessons/v4/migrating-static-templates-into-your-theme-1 and `http://[your-host` a bit further down.
- The code examples sometimes have too much whitespace, and missing closing brackets - e.g. on http://sssites-ssorg-uat.sites.silverstripe.com/learn/lessons/v4/adding-custom-fields-to-a-page-1. They also do omissions a bit weirdly: In the code example following "In this case, we're going to want three new fields", there's a `use` statement that's followed by `// ...`, then indented code. I think this might've worked before without `use`, but now you kinda have to add the `class` construct around it, otherwise people will get confused where the `use` statement goes.
- Some code examples seem to have too much indentation, e.g. the one liners on http://sssites-ssorg-uat.sites.silverstripe.com/learn/lessons/v4/introduction-to-the-orm-1.

**Comment by tractorcow** [comment]
Does this close https://github.com/silverstripe/silverstripe-framework/issues/5972?
