### ISSUE TITLE
Use index.php for routing instead of framework/main.php

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#7430]
# Overview

Follow up after [moving modules into vendor folder](https://github.com/silverstripe/silverstripe-framework/issues/7405), and a precondition to [run webroot in public subfolder](https://github.com/silverstripe/silverstripe-framework/issues/7419). 

We've previously relied on a custom `url` query parameter for routing, which is clunky at best: It means you can't use this as a query parameter in your own payloads, and has security implications around route spoofing. Webservers seem to consistently set `REQUEST_URI` now, or at least there's various ways to get to this information without relying on mod_rewrite (see symfony's [Request.php](https://github.com/symfony/http-foundation/blob/master/Request.php#L1676) for the amount of variations - we should probably support more of them...)

# Acceptance Criteria

 * Serve SilverStripe with only a minimal index.php file in the webroot
 * Support operation on various webservers (incl. ones without rewrite rule support)
 * Upgrading is documented, and as automated as possible
 * Server installation docs are upgraded

# Tasks

 * [x] Fix framework tests
 * [x] Test installer in webroot and subfolder of webroot
 * [x] Fix `Installer.php` references to files
 * [x] Update `index.php` in installer
 * [x] Test and fix IIS operation
 * [x] Test installer and routing without rewrite support (`index.php` based routing)
 * [x] Test protected assets operation
 * [x] Server installation docs
 * [x] Upgrading docs

# Notes

 * Need to adjust staticpublisher module to new routing

# Pull Requests

 * [x] https://github.com/silverstripe/silverstripe-installer/pull/202
 * [x] https://github.com/silverstripe/silverstripe-framework/pull/7432
 * [x] https://github.com/silverstripe/silverstripe-assets/pull/79
 * [x] https://github.com/silverstripe/silverstripe-serve/pull/16
 * [x] https://github.com/silverstripe/recipe-core/pull/6

# Test

```
git clone -b pulls/4/request-uri https://github.com/open-sausages/silverstripe-installer.git 4.clean
cd 4.clean
composer config repositories.framework vcs https://github.com/open-sausages/silverstripe-framework.git
composer config repositories.assets vcs https://github.com/open-sausages/silverstripe-assets.git
composer config repositories.recipe-core vcs https://github.com/open-sausages/recipe-core.git
composer require "silverstripe/framework:dev-pulls/4/request-uri as 4.0.x-dev" "silverstripe/assets:dev-pulls/1/remove-base-path-autodetect as 1.0.x-dev" "silverstripe/recipe-core:dev-pulls/1/request-uri as 1.0.x-dev"
```

**Comment by wernerkrauss** [comment]
+1 for having debugger working in phpstorm without additional setup
