### ISSUE TITLE
SS5: Upgrade to PHPUnit 6.x or 7.x

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-framework#7653]
With SilverStripe 5 will bring newer PHP version requirements, which means dropping at least PHP 5.6 (possibly PHP 7.0 too). This means we can update PHPUnit to either 6.x (current) or [7.x (aiming for Feb 2018).](https://github.com/sebastianbergmann/phpunit/milestones/PHPUnit%207.0)

PHPUnit 6.x lists the following [changes](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0) that are immediately obvious to break for us:

* Drop PHP 5.6 support (fine when we drop it too)
* Introduce namespaced classes e.g. `PHPUnit_Framework_TestCase` -> `PHPUnit\Framework\TestCase`

PHPUnit 7.x (due for Feb 2018 release) also [drops PHP 7.0 support](https://github.com/sebastianbergmann/phpunit/issues/2473) since it's out of active support at the end of 2017 with PHP 5.6.

How do we feel about updating to either PHPUnit 6, or 7 given the PHP version support notes above?

---

## Pull requests

- [x] silverstripe/silverstripe-behat-extension#173
- [x] #7716
- [x] silverstripe/silverstripe-versioned#77
- [x] silverstripe/silverstripe-assets#106
- [x] silverstripe/silverstripe-installer#216
- [x] silverstripe/silverstripe-cms#2073

These were the modules in the core feature set that needed to be updated to support this change in terms of PHPUnit API changes.

The other modules will all need to be updated to increase the minimum PHP version to 7.1, but no test API changes are necessary.

Note that there's a circular dependency between #7716 and silverstripe/silverstripe-behat-extension#173 :)

**Comment by dhensby** [comment]
Do it! :)

**Comment by tractorcow** [comment]
I've just finished updating the test config for 5.x; All related modules (behat-extension etc) are on a separate major verson to 4.x, so we can bump the PHP version dependency as well as phpunit at the same time.

**Comment by robbieaverill** [comment]
Pull requests up :) it'll be a bit of work to review and merge, but everything is passing locally for me.

Biggest implication here is making PHP 7.1 the minimum supported version for SS5, but I think we've already discussed following PHP's support timelines, and 7.0 and lower are now out of active support.

**Comment by mikenz** [comment]
Yay! I started working on this on Friday afternoon. So happy you've done it already :-)

**Comment by robbieaverill** [comment]
Getting through the composer soup will be the hard part ;)

**Comment by tractorcow** [comment]
Had a quick review... let's fix the behat-extension PR, and I can tag an alpha of that module before we update the other recipes.

**Comment by robbieaverill** [comment]
Great, thanks. I've updated the behat-extension pull request and have the installer PR updates ready to push once behat has an alpha tag
