### ISSUE TITLE
Release 4.4.0, 4.4.1

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-framework#9041]
## Subtasks
- [x] Compile a list of known issues
- [x] Post CWP docs update with known issues
- [x] GraphQL security fix submitted
- [x] GraphQL security fix PR/Merge
- [x] Write 4.4.0 blog post
- [x] Write CWP 2.3.0 blog post
- [x] Document file migration limitations in 4.4.0 changelog (prefer 4.4.1)
- [x] Document GraphQL authentication options and CSRF protection
- [x] Add React 16 to changelog
- [x] Merge security fixes (framework, environment-check)
- [x] Let marketing know when release date/time is confirmed
- [x] Merge up 4.2, 4.3 branches
- [x] Do release
- [x] Ensure new minor release is visible on doc.silverstripe.org, userhelp.silverstripe.org
- [x] Forum post
- [x] Slack channel message
- [x] Disclose security fixes

**Comment by unclecheese** [comment]
## Known issues
(high impact bugs that have been raised since the last CWP release and are as yet unresolved -- to be merged into CWP docs)

https://github.com/silverstripe/silverstripe-cms/issues/2432
https://github.com/silverstripe/silverstripe-framework/issues/9029
https://github.com/silverstripe/silverstripe-framework/issues/8871
https://github.com/silverstripe/silverstripe-framework/issues/8867
https://github.com/silverstripe/silverstripe-framework/issues/8792
https://github.com/silverstripe/silverstripe-framework/issues/8785
https://github.com/silverstripe/silverstripe-asset-admin/issues/930
https://github.com/silverstripe/silverstripe-asset-admin/issues/903
https://github.com/silverstripe/silverstripe-assets/issues/276
https://github.com/silverstripe/silverstripe-assets/issues/247
https://github.com/silverstripe/silverstripe-assets/issues/220
https://github.com/silverstripe/silverstripe-cms/issues/2426
https://github.com/silverstripe/silverstripe-cms/issues/2415
https://github.com/silverstripe/silverstripe-versioned/issues/200
https://github.com/silverstripe/silverstripe-graphql/issues/217
https://github.com/silverstripe/silverstripe-admin/issues/886
https://github.com/silverstripe/silverstripe-admin/issues/827
https://github.com/silverstripe/silverstripe-admin/issues/826
https://github.com/silverstripe/silverstripe-admin/issues/825
https://github.com/silverstripe/silverstripe-admin/issues/823
https://github.com/silverstripe/silverstripe-admin/issues/808
https://github.com/silverstripe/silverstripe-versioned-admin/issues/95

**Comment by kinglozzer** [comment]
Raised on Slack - there doesn’t appear to be a `4.4.1` changelog. Not a major issue as not much has changed of course, just thought I’d raise it here as I thought they were automatically generated as part of the release

**Comment by Juanitou** [comment]
A minor issue with the `4.4.0` changelog: The link to the security patch for SS-2018-022 is broken, and I have not found a valid one. The identifier 2018-22 is not found in the Security Releases page.

**Comment by michalkleiner** [comment]
Yes, the Security Releases page doesn't have anchors based on titles, so it's not possible to link to a specific one. Looked at that yesterday.
