### ISSUE TITLE
Run PHP 7.4 automation tests on all core modules

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-framework#9116]
## Acceptance Criteria

 * Every module included in `silverstripe-installer` runs on PHP 7.4, individually
 * Builds are added for both 3.x and 4.x versions. Note `framework 3.x` is [already running these builds](https://github.com/silverstripe/silverstripe-framework/issues/9208)
 * There is no composer constraint limiting the module use to a version less than PHP 7
 * All builds are passing for 4.x. 
 * All failing builds in SS3 are split into new issues for tackling in the future.

## Notes

 * Framework already runs on PHP 7.4 ~~after resolving a [PHPUnit blocker](https://github.com/silverstripe/silverstripe-framework/issues/9062)~~
 * Opened the same issue for PHP 7.2 and 7.3 at https://github.com/silverstripe/silverstripe-framework/issues/8864 a while ago
 * ~~Using `php: 7.4snapshot` in Travis now means we might need to change a lot of `.travis.yml` to `php: 7.4` once it's released, but on balance it's better to get a heads up on any potential PHP 7.4 issues than being caught out by them once the stable release is out~~ Travis now supports PHP 7.4 stable, so we can target this

### Tasks

- [x] Apply PHP 7.4 build to the `4.5` / `4` / `master` branches of every module contained in `silverstripe/installer` (ensure all builds are green before merging these PRs)
- [x] Smoke test a 4.x install of `cwp/cwp-recipe-kitchen-sink`
- [x] Raise PRs to apply PHP 7.4 build to the `3.7` / `3` branches of every module contained in `silverstripe/installer` 
- [x] Raise issue to resolve failing builds on 7.4 PRs to `3.7` / `3`

#### 4.x

- [x] [silverstripe/assets](https://github.com/silverstripe/silverstripe-assets/pull/376) **merged up**
- [x] [silverstripe/config](https://github.com/silverstripe/silverstripe-config/pull/40) **merged up**
- [x] [silverstripe/framework](https://github.com/silverstripe/silverstripe-framework/pull/9412) **merged up**
- [x] [silverstripe/admin](https://github.com/silverstripe/silverstripe-admin/pull/1014) **merged up**
- [x] [silverstripe/asset-admin](https://github.com/silverstripe/silverstripe-asset-admin/pull/1064) **merged up**
- [x] [silverstripe/campaign-admin](https://github.com/silverstripe/silverstripe-campaign-admin/pull/157) **merged up**
- [x] [silverstripe/versioned-admin](https://github.com/silverstripe/silverstripe-versioned-admin/pull/150) **merged up**
- [x] [silverstripe/cms](https://github.com/silverstripe/silverstripe-cms/pull/2528) **merged up**
- [x] [silverstripe/errorpage](https://github.com/silverstripe/silverstripe-errorpage/pull/48) **merged up**
- [x] [silverstripe/graphql](https://github.com/silverstripe/silverstripe-graphql/pull/251) **merged up**
- [x] [silverstripe/reports](https://github.com/silverstripe/silverstripe-reports/pull/124) **merged up**
- [x] [silverstripe/siteconfig](https://github.com/silverstripe/silverstripe-siteconfig/pull/109) **merged up**
- [x] [silverstripe/versioned](https://github.com/silverstripe/silverstripe-versioned/pull/266) **merged up**
- [x] [silverstripe/recipe-core](https://github.com/silverstripe/recipe-core/pull/52) **merged up**
- [x] [silverstripe/recipe-cms](https://github.com/silverstripe/recipe-cms/pull/31) **merged up**
- [x] [silverstripe/installer](https://github.com/silverstripe/silverstripe-installer/pull/275) **merged up**

#### 3.x

- [ ] [silverstripe/framework](https://github.com/silverstripe/silverstripe-framework/pull/9420)
- [ ] [silverstripe/cms](https://github.com/silverstripe/silverstripe-cms/pull/2529)
- [x] [silverstripe/reports](https://github.com/silverstripe/silverstripe-reports/pull/125)
- [x] [silverstripe/siteconfig](https://github.com/silverstripe/silverstripe-siteconfig/pull/110)

**Comment by chillu** [comment]
PHP 7.4 has been released today

**Comment by brynwhyman** [comment]
The following WIP PR will merge 7.4 builds into our kitchen sink test suite: https://github.com/silverstripe/cwp-recipe-kitchen-sink/pull/49 (although we'll still want to update the core modules separately)

**Comment by chillu** [comment]
Just to clarify: Are we doing this for module both on the 1.x and 2.x recipe? We've already got 7.4 builds on `framework:3.x` (see [issue](https://github.com/silverstripe/silverstripe-framework/issues/9208)) so sounds like that decision has been made at least for the module already.

**Comment by brynwhyman** [comment]
@chillu I think we should be looking at 7.4 compatibility for v3.x (and the CWP 1.x recipe) as well, especially if the current test failures look to only be as a result of PHP depreciations.

**Comment by Cheddam** [comment]
PRs for both 4.x and 3.x have been raised, with the 4.x ones already merged. I've raised a follow-up issue to get the 3.x PRs green and merged: #9421

Remaining effort is merging up `4.5` branches to `4` and `master`.
